-- 关闭所有表的行级安全（后端应用不需要 RLS）
ALTER TABLE health_check DISABLE ROW LEVEL SECURITY;
ALTER TABLE prediction_data DISABLE ROW LEVEL SECURITY;
ALTER TABLE match_odds DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE prediction_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE learned_patterns DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE memory_bank DISABLE ROW LEVEL SECURITY;
