import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
type Row=Record<string,unknown>;
const db=vi.hoisted(()=>({users:[] as Row[],sessions:[] as Row[],audits:[] as Row[],reservations:new Map<string,Row>()}));
vi.mock("@/storage/database/supabase-client",()=>{
 class Q implements PromiseLike<{data:unknown;error:null;count?:number}>{f:Array<[string,unknown]>=[];nil:string[]=[];ins:Row|null=null;upd:Row|null=null;count=false;constructor(private t:string){}select(_c?:string,o?:{count?:string}){this.count=o?.count==="exact";return this}eq(k:string,v:unknown){this.f.push([k,v]);return this}is(k:string,v:unknown){if(v===null)this.nil.push(k);return this}order(){return this}insert(v:Row){this.ins=v;return this}update(v:Row){this.upd=v;return this}rows(){return(this.t==="admin_users"?db.users:this.t==="admin_sessions"?db.sessions:db.audits)}run(){if(this.ins){this.rows().push(this.ins);return{data:[this.ins],error:null}}const r=this.rows().filter(x=>this.f.every(([k,v])=>x[k]===v)&&this.nil.every(k=>x[k]==null));if(this.upd)r.forEach(x=>Object.assign(x,this.upd));return{data:r,error:null,count:this.count?r.length:undefined}}async maybeSingle(){const x=this.run().data[0]||null;if(x&&this.t==="admin_sessions"){const u=db.users.find(y=>y.id===x.admin_user_id);return{data:{...x,admin_users:u&&{is_active:u.is_active,role:u.role,username:u.username}},error:null}}return{data:x,error:null}}async single(){return this.maybeSingle()}then<A={data:unknown;error:null;count?:number},B=never>(ok?:((v:{data:unknown;error:null;count?:number})=>A|PromiseLike<A>)|null,bad?:((r:unknown)=>B|PromiseLike<B>)|null){return Promise.resolve(this.run()).then(ok,bad)}}
 return{getSupabaseClient:()=>({from:(t:string)=>new Q(t),rpc:async(name:string,args:Row)=>{if(name==="bootstrap_first_admin"){if(db.users.length)return{data:null,error:{message:"ADMIN_ALREADY_INITIALIZED"}};const now=new Date().toISOString();const row={id:args.p_id,username:args.p_username,display_name:args.p_display_name,password_hash:args.p_password_hash,role:"super_admin",is_active:true,last_login_at:null,created_at:now,updated_at:now};db.users.push(row);return{data:[row],error:null}}if(name==="reserve_admin_login_attempt_v2"){db.reservations.set(String(args.p_reservation_key),args);return{data:[{allowed:true,retry_after_seconds:0,reservation_key:args.p_reservation_key}],error:null}}if(name==="settle_admin_login_attempt_v2"){const existed=db.reservations.delete(String(args.p_reservation_key));return{data:[{settled:existed,audit_failure:args.p_succeeded===false}],error:null}}return{data:null,error:{message:"unsupported rpc"}}}})}});
import { DELETE,GET,POST } from "@/app/api/auth/session/route";
import { POST as BOOTSTRAP } from "@/app/api/auth/bootstrap/route";
import { hashAdminPassword } from "@/lib/auth/password";
const old=process.env.ADMIN_API_TOKEN;const oldLegacy=process.env.ADMIN_LEGACY_BOOTSTRAP_ENABLED;const oldRateSecret=process.env.ADMIN_LOGIN_RATE_LIMIT_SECRET;
const req=(method:"POST"|"DELETE",body?:Row,cookie?:string)=>new NextRequest("https://app.invalid/api/auth/session",{method,headers:{origin:"https://app.invalid","content-type":"application/json",...(cookie?{cookie}:{})},body:body?JSON.stringify(body):undefined});
describe("persistent administrator identity flow",()=>{
 beforeEach(async()=>{db.users=[{id:"admin-1",username:"root.admin",display_name:"Root",password_hash:await hashAdminPassword("CorrectPassword123"),role:"super_admin",is_active:true,last_login_at:null,created_at:"2026-07-15",updated_at:"2026-07-15"}];db.sessions=[];db.audits=[];db.reservations.clear();process.env.ADMIN_API_TOKEN="legacy-recovery-token";process.env.ADMIN_LOGIN_RATE_LIMIT_SECRET="test-rate-limit-secret-with-at-least-32-characters"});
 afterEach(()=>{if(old===undefined)delete process.env.ADMIN_API_TOKEN;else process.env.ADMIN_API_TOKEN=old;if(oldLegacy===undefined)delete process.env.ADMIN_LEGACY_BOOTSTRAP_ENABLED;else process.env.ADMIN_LEGACY_BOOTSTRAP_ENABLED=oldLegacy;if(oldRateSecret===undefined)delete process.env.ADMIN_LOGIN_RATE_LIMIT_SECRET;else process.env.ADMIN_LOGIN_RATE_LIMIT_SECRET=oldRateSecret});
 it("authenticates account credentials and persists a reusable session",async()=>{const login=await POST(req("POST",{username:" ROOT.ADMIN ",password:"CorrectPassword123"}));const cookie=(login.headers.get("set-cookie")||"").split(";")[0];expect(login.status).toBe(200);expect(await login.json()).toMatchObject({user:{id:"admin-1",role:"super_admin"}});expect(db.sessions).toHaveLength(1);expect(db.sessions[0].token_hash).toMatch(/^[a-f0-9]{64}$/);const status=await GET(new NextRequest("https://app.invalid/api/auth/session",{headers:{cookie}}));expect(status.status).toBe(200);expect(await status.json()).toMatchObject({authenticated:true,user:{id:"admin-1"}})});
 it("returns the same error for unknown account and wrong password",async()=>{const a=await POST(req("POST",{username:"missing.user",password:"CorrectPassword123"}));const b=await POST(req("POST",{username:"root.admin",password:"WrongPassword123"}));expect([a.status,b.status]).toEqual([401,401]);expect(await a.json()).toEqual(await b.json());expect(a.headers.get("set-cookie")).toBeNull()});
 it("revokes logout server-side and reports explicit unauthenticated reuse",async()=>{const login=await POST(req("POST",{username:"root.admin",password:"CorrectPassword123"}));const cookie=(login.headers.get("set-cookie")||"").split(";")[0];expect((await DELETE(req("DELETE",undefined,cookie))).status).toBe(200);expect(db.sessions[0].revoked_at).toEqual(expect.any(String));const probe=await GET(new NextRequest("https://app.invalid/api/auth/session",{headers:{cookie}}));expect(probe.status).toBe(200);expect(await probe.json()).toMatchObject({authenticated:false,user:null})});
 it("rejects the legacy shared token after accounts exist",async()=>{const r=await POST(req("POST",{username:"missing.user",password:"legacy-recovery-token",token:"legacy-recovery-token"}));expect(r.status).toBe(401);expect(r.headers.get("set-cookie")).toBeNull()});
 it("keeps legacy bootstrap disabled by default",async()=>{db.users=[];delete process.env.ADMIN_LEGACY_BOOTSTRAP_ENABLED;const r=await BOOTSTRAP(new NextRequest("https://app.invalid/api/auth/bootstrap",{method:"POST",headers:{origin:"https://app.invalid","content-type":"application/json"},body:JSON.stringify({bootstrapToken:"legacy-recovery-token",username:"first.admin",password:"FirstPassword123"})}));expect(r.status).toBe(401);expect(db.users).toHaveLength(0)});
 it("allows the explicitly enabled legacy token only to bootstrap an empty installation",async()=>{db.users=[];process.env.ADMIN_LEGACY_BOOTSTRAP_ENABLED="true";const r=await BOOTSTRAP(new NextRequest("https://app.invalid/api/auth/bootstrap",{method:"POST",headers:{origin:"https://app.invalid","content-type":"application/json"},body:JSON.stringify({bootstrapToken:"legacy-recovery-token",username:"first.admin",password:"FirstPassword123"})}));expect(r.status).toBe(201);expect(db.users).toHaveLength(1);expect(db.users[0]).toMatchObject({username:"first.admin",role:"super_admin"})});
 it("refuses enabled legacy-token bootstrap after any account exists",async()=>{process.env.ADMIN_LEGACY_BOOTSTRAP_ENABLED="true";const r=await BOOTSTRAP(new NextRequest("https://app.invalid/api/auth/bootstrap",{method:"POST",headers:{origin:"https://app.invalid","content-type":"application/json"},body:JSON.stringify({bootstrapToken:"legacy-recovery-token",username:"second.admin",password:"SecondPassword123"})}));expect(r.status).toBe(409);expect(db.users).toHaveLength(1)});
});
