import { beforeEach,describe,expect,it,vi } from "vitest";
import { NextRequest } from "next/server";
const mocks=vi.hoisted(()=>({create:vi.fn(),update:vi.fn(),get:vi.fn(),audit:vi.fn()}));
vi.mock("@/lib/auth/admin-capabilities",()=>({requireAdminCapability:vi.fn(async()=>({ok:true,principal:{actorId:"managing-super",actorType:"admin",role:"super_admin",capabilities:["admin:manage"]}}))}));
vi.mock("@/lib/auth/admin-accounts",()=>{class Conflict extends Error{};return{AdminUserUpdateConflictError:Conflict,isAdminRole:(v:unknown)=>["super_admin","operator","auditor"].includes(String(v)),createAdminUser:mocks.create,updateAdminUser:mocks.update,getAdminUser:mocks.get}});
import { POST } from "@/app/api/admin/users/route";
import { PATCH } from "@/app/api/admin/users/[id]/route";
const request=(url:string,method:"POST"|"PATCH",body:unknown)=>new NextRequest(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});
describe("administrator user API guardrails",()=>{
 beforeEach(()=>{vi.clearAllMocks();mocks.audit.mockResolvedValue(true);mocks.get.mockResolvedValue({id:"other-super",username:"root",displayName:"Root",role:"super_admin",isActive:true,updatedAt:"2026-07-15T00:00:00.000Z"})});
 it("rejects weak passwords with the stable safe error shape",async()=>{const response=await POST(request("https://app.invalid/api/admin/users","POST",{username:"operator.one",password:"short1",role:"operator"}));expect(response.status).toBe(400);expect(await response.json()).toMatchObject({success:false,errorCode:"INVALID_PASSWORD",message:"密码至少需要 12 个字符",requestId:expect.any(String)});expect(mocks.create).not.toHaveBeenCalled()});
 it.each([{role:"operator"},{isActive:false}])("maps the database last-super guard to a safe conflict: %o",async changes=>{mocks.update.mockRejectedValue(new Error("不能停用或降级最后一个超级管理员"));const response=await PATCH(request("https://app.invalid/api/admin/users/other-super","PATCH",{...changes,expectedUpdatedAt:"2026-07-15T00:00:00.000Z"}),{params:Promise.resolve({id:"other-super"})});expect(response.status).toBe(409);expect(await response.json()).toMatchObject({success:false,errorCode:"LAST_ACTIVE_SUPER_ADMIN",message:"不能停用或降级最后一个超级管理员"});expect(mocks.update).toHaveBeenCalledOnce()});
 it("requires an administrator version precondition",async()=>{const response=await PATCH(request("https://app.invalid/api/admin/users/other-super","PATCH",{role:"auditor"}),{params:Promise.resolve({id:"other-super"})});expect(response.status).toBe(400);expect(await response.json()).toMatchObject({success:false,errorCode:"INVALID_ADMIN_VERSION",message:"缺少有效的管理员数据版本"});expect(mocks.update).not.toHaveBeenCalled()});
 it("returns a safe optimistic concurrency conflict without leaking the latest object",async()=>{const accounts=await import("@/lib/auth/admin-accounts");mocks.update.mockRejectedValue(new accounts.AdminUserUpdateConflictError());const response=await PATCH(request("https://app.invalid/api/admin/users/other-super","PATCH",{role:"super_admin",expectedUpdatedAt:"2026-07-15T00:00:00.000Z"}),{params:Promise.resolve({id:"other-super"})});expect(response.status).toBe(409);const body=await response.json();expect(body).toMatchObject({success:false,errorCode:"ADMIN_UPDATE_CONFLICT",message:"管理员数据已被其他操作更新，请刷新后重试"});expect(body).not.toHaveProperty("user")});
 it("does not expose schema or upstream failures",async()=>{mocks.create.mockRejectedValue(new Error("relation admin_users does not exist; upstream token=secret"));const response=await POST(request("https://app.invalid/api/admin/users","POST",{username:"operator.one",password:"StrongPassword-123",role:"operator"}));expect(response.status).toBe(500);const body=await response.json();expect(body).toMatchObject({errorCode:"ADMIN_CREATE_FAILED",message:"管理员创建失败"});expect(JSON.stringify(body)).not.toMatch(/admin_users|upstream|secret/) });
});
