import { readFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
const read=(file:string)=>readFile(new URL(`../${file}`,import.meta.url),"utf8");
const exec=promisify(execFile);
const dynamicResult=exec("bash",["tests/candidate-stage-p0-dynamic.sh"],{cwd:process.cwd(),timeout:60000,env:{...process.env,PEILV_TEST_SANDBOX_ONLY:"1"}});
const callers=["scripts/deploy-production.sh","scripts/rollback-production.sh"];

describe("P0-1 candidate private network and finite resources",()=>{
 it("uses MainPID plus nsenter readiness and has no host-loopback candidate probe",async()=>{const h=await read("scripts/lib/candidate-lifecycle.sh");expect(h).toMatch(/PrivateNetwork=(?:yes|true)/);expect(h).toMatch(/systemctl show[^\n]*MainPID/);expect(h).toMatch(/nsenter[^\n]*(?:-t|--target)[^\n]*(?:pid|MainPID)/i);expect(h).toMatch(/nsenter[^\n]*127\.0\.0\.1:\$port\/api\/readiness/);expect(h).not.toMatch(/^(?!.*nsenter).*curl[^\n]*127\.0\.0\.1:5001/m)});
 it("sets finite memory, task, CPU and fd limits",async()=>{const h=await read("scripts/lib/candidate-lifecycle.sh");for(const key of ["MemoryMax=","TasksMax=","CPUQuota=","LimitNOFILE="])expect(h).toContain(key);for(const line of ['CANDIDATE_MEMORY_MAX="${PEILV_CANDIDATE_MEMORY_MAX:-768M}"','CANDIDATE_TASKS_MAX="${PEILV_CANDIDATE_TASKS_MAX:-128}"','CANDIDATE_CPU_QUOTA="${PEILV_CANDIDATE_CPU_QUOTA:-100%}"','CANDIDATE_NOFILE="${PEILV_CANDIDATE_NOFILE:-4096}"'])expect(h).toContain(line)});
 it.each(callers)("sources and exclusively uses shared lifecycle: %s",async file=>{const s=await read(file);expect(s).toContain("candidate-lifecycle.sh");expect(s).toContain("candidate_wait_ready");expect(s).toContain("candidate_stop_and_release")});
});

describe("P0-2 rollback remains pre-transaction through every candidate gate",()=>{
 it("places stage/hash/start/readiness/log/stop before transaction and all formal mutations",async()=>{const s=await read("scripts/rollback-production.sh"),stage=s.indexOf("candidate_prepare_stage"),hash=s.indexOf("verify-release.sh --tree",stage),start=s.indexOf("candidate_start",stage),ready=s.indexOf("candidate_wait_ready",start),log=s.indexOf("journalctl",ready),stop=s.indexOf("stop_candidate",log),tx=s.indexOf("transaction_started=1",stop);for(const x of [stage,hash,start,ready,log,stop,tx])expect(x).toBeGreaterThan(-1);expect(stage).toBeLessThan(hash);expect(hash).toBeLessThan(start);expect(start).toBeLessThan(ready);expect(ready).toBeLessThan(log);expect(log).toBeLessThan(stop);expect(stop).toBeLessThan(tx);for(const token of ["systemctl stop peilv.service","systemctl stop peilv-dispatch.timer",'mv -Tf "$base/current.next"',"systemctl reload openresty.service","write_transaction_state maintenance_entering"]){const i=s.indexOf(token,tx);expect(i===-1||i>tx).toBe(true)}});
 it("executes six isolated rollback faults with zero formal mutations",async()=>{const d=await read("tests/candidate-stage-p0-dynamic.sh");expect(d).toContain("run_rollback_fault");expect(d).toContain("rollback_candidate_pretransaction");expect(d).toContain("formal-$1.log");const {stdout,stderr}=await dynamicResult;expect(stderr).toBe("");const lines=stdout.trim().split(/\r?\n/).filter(line=>/^PASS rollback_zero_mutation_/.test(line));expect(lines).toHaveLength(6);expect(new Set(lines).size).toBe(6);for(const x of ["stage","ENOSPC","hash","start","readiness","log"])expect(lines).toContain(`PASS rollback_zero_mutation_${x} calls=0`)},70000);
});

describe("P0-3 peak filesystem budget, serialization and durable backup",()=>{
 it("aggregates blocks and inodes by device and enforces quota",async()=>{const h=await read("scripts/lib/deployment-budget.sh");expect(h).toContain("stat -c '%d'");expect(h).toMatch(/DEPLOY_BUDGET_KIB\[\$device\].*\+ kib/);expect(h).toMatch(/DEPLOY_BUDGET_INODES\[\$device\].*\+ inodes/);expect(h).toContain("df -Pk");expect(h).toContain("df -Pi");expect(h).toMatch(/quota|xfs_quota/);expect(h).toMatch(/return 1|exit 1/)});
 it.each(["scripts/production-preflight.sh",...callers])("takes deploy flock before budget/staging: %s",async file=>{const s=await read(file),lock=s.indexOf("flock -n"),budget=Math.min(...["deployment_budget_check","candidate_prepare_stage"].map(x=>{const i=s.indexOf(x);return i<0?Number.MAX_SAFE_INTEGER:i}));expect(lock).toBeGreaterThan(-1);expect(lock).toBeLessThan(budget)});
 it("injects same-filesystem blocks, inodes, quota and lock contention",async()=>{const d=await read("tests/candidate-stage-p0-dynamic.sh");for(const x of ["same_filesystem_peak_blocks","same_filesystem_peak_inodes","quota_exhausted","flock_contended"])expect(d).toContain(x)});
 it("backs up via partial, validation, fsync and atomic rename",async()=>{const s=await read("scripts/deploy-production.sh"),a=s.indexOf('backup_partial="$backup.partial"'),dump=s.indexOf("pg_dump",a),verify=s.indexOf("pg_restore -l",dump),sync=s.indexOf("sync -f",verify),rename=s.indexOf('mv -T "$backup_partial" "$backup"',sync);expect(a).toBeGreaterThan(-1);expect(a).toBeLessThan(dump);expect(dump).toBeLessThan(verify);expect(verify).toBeLessThan(sync);expect(sync).toBeLessThan(rename)});
});

describe("P0-4 stubborn shutdown, cleanup, quarantine and groups",()=>{
  it("proves inactive MainPID zero, 5001 closed and pin unmounted before release",async()=>{const h=await read("scripts/lib/candidate-lifecycle.sh"),a=h.indexOf("candidate_stop_and_release()"),body=h.slice(a);expect(body).toMatch(/timeout[^\n]*systemctl stop "\$unit"/);expect(body).toContain("candidate_wait_inactive");expect(body).toContain("MainPID");expect(body).toContain('[[ "$pid" == 0 ]]');expect(body).toContain("sport = :5001");expect(body).toContain('umount "$pin"');expect(body).toMatch(/!\s+mountpoint -q "\$pin"|findmnt[^\n]*\$pin[^\n]*(?:return 1|exit 1)/)});
 it.each(callers)("preserves stage when lifecycle proof fails: %s",async file=>{const s=await read(file),a=s.indexOf("stop_candidate() {"),b=s.indexOf("check_candidate_application()",a),body=s.slice(a,b);expect(body).toMatch(/candidate_stop_and_release[^]*\|\|\s*\{/);expect(body.indexOf("return 1")).toBeLessThan(body.indexOf("candidate_cleanup_stage",body.indexOf("candidate_stop_and_release")))});
 it("dynamically injects TERM-ignore, stop timeout, live PID, 5001 and busy mount",async()=>{const d=await read("tests/candidate-stage-p0-dynamic.sh");expect(d).toContain("run_stop_fault");const {stdout,stderr}=await dynamicResult;expect(stderr).toBe("");const lines=stdout.trim().split(/\r?\n/).filter(line=>/^PASS (?:ignore_TERM|systemctl_stop_timeout|MainPID_alive|port_5001_listening|mount_busy) /.test(line));expect(lines).toHaveLength(5);expect(new Set(lines).size).toBe(5);for(const x of ["ignore_TERM","systemctl_stop_timeout","MainPID_alive","port_5001_listening","mount_busy"])expect(lines).toContain(`PASS ${x} stage_preserved=1`)},70000);
 it("preflight registers verified tree for recursive cleanup",async()=>{const p=await read("scripts/production-preflight.sh");expect(p).toMatch(/cleanup_temp_files\(\)[^\n]*rm -rf --one-file-system/);expect(p).toContain('register_temp_file "$verified_tree"');expect(p.indexOf('register_temp_file "$verified_tree"')).toBeLessThan(p.indexOf("verify-release.sh --archive"))});
 it("quarantines failed release before current switching",async()=>{const s=await read("scripts/deploy-production.sh"),q=s.search(/quarantine|rejected-releases|failed-releases/i),current=s.indexOf('mv -Tf "$base/current.next"');expect(q).toBeGreaterThan(-1);expect(q).toBeLessThan(current)});
 it("requires formal accounts in peilv and candidate only in isolated group",async()=>{const p=await read("scripts/production-preflight.sh");for(const x of ["peilv-app","peilv-reconcile","peilv-dispatch","peilv-probe"])expect(p).toContain(x);expect(p).toContain('[[ "$(id -gn peilv-candidate)" == peilv-candidate ]]');expect(p).toContain('[[ "$(id -nG peilv-candidate)" == peilv-candidate ]]')});
});
