import { describe, expect, it, vi } from "vitest";
import { AuditPersistenceError, CommandConflictError, type CommandReceipt, type CommandRepository } from "@/features/management/commands";
import { executeDeploymentDispatch } from "@/lib/release-control/dispatch-command";

const principal = { actorId: "admin:test", actorType: "admin" as const, capabilities: ["admin:dangerous" as const] };
const audit = vi.fn(async()=>true);
function repository(): CommandRepository {
  const rows = new Map<string, CommandReceipt>();
  return {
    async begin(action, command, hash) { const key=`${action}:${command.idempotencyKey}`;const existing=rows.get(key);if(existing)return {created:false,receipt:existing};const receipt={status:"accepted",request_hash:hash,result_reference:null,safe_error:null} as CommandReceipt;rows.set(key,receipt);return {created:true,receipt}; },
    async transition(action,key,from,to,result){const value=rows.get(`${action}:${key}`)!;if(!from.includes(value.status))throw new Error("invalid transition");rows.set(`${action}:${key}`,{...value,status:to,...(result===undefined?{}:{result_reference:result})});},
    async succeed(action,key,result){const value=rows.get(`${action}:${key}`)!;rows.set(`${action}:${key}`,{...value,status:"completed",result_reference:result});},
    async recordEffectResult(action,key,result){const value=rows.get(`${action}:${key}`)!;rows.set(`${action}:${key}`,{...value,result_reference:result,audit_context:{...(value.audit_context||{}),effectSucceeded:true}});},
    async fail(action,key,error){const value=rows.get(`${action}:${key}`)!;rows.set(`${action}:${key}`,{...value,status:"failed",safe_error:error});},
  };
}
const command=(payload:Record<string,unknown>={releaseId:"r10-a1-aaaaaaaaaaaa"})=>({idempotencyKey:"deploy-key-0001",reason:"专项测试部署",payload});

describe("deployment persistent dispatch claim",()=>{
  it("rejects actions outside the deployment registry with audit",async()=>{const localAudit=vi.fn(async()=>true);await expect(executeDeploymentDispatch({action:"deployment.unknown",command:command(),principal,requestId:"one",repository:repository(),audit:localAudit,execute:async()=>({ok:true})})).rejects.toThrow("未知部署管理命令");expect(localAudit).toHaveBeenCalledWith(expect.objectContaining({action:"deployment.unknown.rejected"}));});
  it("enforces the registry capability with audit",async()=>{const localAudit=vi.fn(async()=>true);await expect(executeDeploymentDispatch({action:"deployment.deploy",command:command(),principal:{...principal,capabilities:["admin:view"]},requestId:"one",repository:repository(),audit:localAudit,execute:async()=>({ok:true})})).rejects.toThrow("权限不足");expect(localAudit).toHaveBeenCalledWith(expect.objectContaining({action:"deployment.deploy.rejected"}));});
  it.each([
    ["registry", "deployment.unknown", principal],
    ["capability", "deployment.deploy", {...principal,capabilities:["admin:view" as const]}],
  ])("fails closed when %s rejected audit returns false",async(_caseName,action,actor)=>{const provider=vi.fn(async()=>({ok:true}));const operation=executeDeploymentDispatch({action,command:command(),principal:actor,requestId:"rejected-audit-false",repository:repository(),audit:vi.fn(async()=>false),execute:provider});await expect(operation).rejects.toBeInstanceOf(AuditPersistenceError);await expect(operation).rejects.toMatchObject({status:503});expect(provider).not.toHaveBeenCalled();});
  it("persists requested audit before provider dispatch",async()=>{const order:string[]=[];const localAudit=vi.fn(async entry=>{order.push(entry.action);return true});const provider=vi.fn(async()=>{order.push("provider");return {ok:true}});await executeDeploymentDispatch({action:"deployment.deploy",command:command(),principal,requestId:"requested-first",repository:repository(),audit:localAudit,execute:provider});expect(order).toEqual(["deployment.deploy.requested","provider","deployment.deploy.succeeded"]);expect(provider).toHaveBeenCalledTimes(1);});
  it("does not call provider when requested audit returns false and does not retry the same key",async()=>{const receipts=repository();const provider=vi.fn(async()=>({ok:true}));const first=executeDeploymentDispatch({action:"deployment.deploy",command:command(),principal,requestId:"requested-audit-false",repository:receipts,audit:vi.fn(async()=>false),execute:provider});await expect(first).rejects.toBeInstanceOf(AuditPersistenceError);await expect(executeDeploymentDispatch({action:"deployment.deploy",command:command(),principal,requestId:"requested-replay",repository:receipts,audit:vi.fn(async()=>true),execute:provider})).rejects.toThrow("审计记录写入失败");expect(provider).not.toHaveBeenCalled();});
  it("replays identical payload without dispatching twice",async()=>{const receipts=repository();const dispatch=vi.fn(async()=>({requestId:"request-1"}));const input={action:"deployment.deploy",command:command(),principal,requestId:"request-1",repository:receipts,audit,execute:dispatch};expect((await executeDeploymentDispatch(input)).replayed).toBe(false);expect((await executeDeploymentDispatch(input)).replayed).toBe(true);expect(dispatch).toHaveBeenCalledTimes(1);});
  it("rejects same key with another canonical payload",async()=>{const receipts=repository();await executeDeploymentDispatch({action:"deployment.deploy",command:command(),principal,requestId:"one",repository:receipts,audit,execute:async()=>({ok:true})});await expect(executeDeploymentDispatch({action:"deployment.deploy",command:command({releaseId:"r11-a1-bbbbbbbbbbbb"}),principal,requestId:"two",repository:receipts,audit,execute:async()=>({ok:true})})).rejects.toBeInstanceOf(CommandConflictError);});
  it("allows one concurrent dispatcher and returns its durable state",async()=>{const receipts=repository();let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve});const dispatch=vi.fn(async()=>{await gate;return {ok:true}});const input={action:"deployment.preflight",command:command(),principal,requestId:"one",repository:receipts,audit,execute:dispatch};const first=executeDeploymentDispatch(input);await Promise.resolve();expect((await executeDeploymentDispatch(input)).replayed).toBe(true);release();await first;expect(dispatch).toHaveBeenCalledTimes(1);});
  it("persists redacted failed audit when dispatch fails",async()=>{const localAudit=vi.fn(async()=>true);await expect(executeDeploymentDispatch({action:"deployment.rollback",command:command({targetReleaseId:"r9-a1-aaaaaaaaaaaa",token:"secret"}),principal,requestId:"one",repository:repository(),audit:localAudit,execute:async()=>{throw new Error("provider unavailable");}})).rejects.toThrow("provider unavailable");expect(localAudit).toHaveBeenCalledWith(expect.objectContaining({action:"deployment.rollback.failed",metadata:expect.objectContaining({error:"provider unavailable"})}));});
  it("fails closed when provider-failed audit returns false and never repeats provider dispatch",async()=>{const receipts=repository();const provider=vi.fn(async()=>{throw new Error("provider validation failed")});const localAudit=vi.fn(async entry=>entry.action.endsWith(".requested"));const first=executeDeploymentDispatch({action:"deployment.preflight",command:command(),principal,requestId:"failed-audit-false",repository:receipts,audit:localAudit,execute:provider});await expect(first).rejects.toBeInstanceOf(AuditPersistenceError);await expect(executeDeploymentDispatch({action:"deployment.preflight",command:command(),principal,requestId:"failed-replay",repository:receipts,audit:vi.fn(async()=>true),execute:provider})).rejects.toThrow("provider validation failed");expect(provider).toHaveBeenCalledTimes(1);});
  it("recovers audit_pending on identical retry and never dispatches twice",async()=>{const receipts=repository();const execute=vi.fn(async()=>({ok:true}));const outcomeAuditFails=vi.fn().mockResolvedValueOnce(true).mockResolvedValueOnce(false);const first=await executeDeploymentDispatch({action:"deployment.deploy",command:command(),principal,requestId:"one",repository:receipts,audit:outcomeAuditFails,execute});expect(first.commandStatus).toBe("audit_pending");const replay=await executeDeploymentDispatch({action:"deployment.deploy",command:command(),principal,requestId:"two",repository:receipts,audit,execute});expect(replay.commandStatus).toBe("completed");expect(replay.replayed).toBe(true);expect(execute).toHaveBeenCalledTimes(1);});
  it("returns durable unknown instead of failed when provider succeeded but receipt transition is uncertain",async()=>{const receipts=repository();const original=receipts.transition;let uncertain=true;receipts.transition=vi.fn(async(action,key,from,to,result)=>{if(to==="effect_succeeded"&&uncertain){uncertain=false;throw new Error("receipt timeout")}return original(action,key,from,to,result)});const execute=vi.fn(async()=>({providerId:"once"}));const result=await executeDeploymentDispatch({action:"deployment.deploy",command:command(),principal,requestId:"one",repository:receipts,audit,execute});expect(result.commandStatus).toBe("receipt_persistence_uncertain");expect(result.result).toEqual({providerId:"once"});const replay=await executeDeploymentDispatch({action:"deployment.deploy",command:command(),principal,requestId:"two",repository:receipts,audit,execute});expect(replay.commandStatus).toBe("completed");expect(execute).toHaveBeenCalledOnce();});
  it("keeps a provider success recoverable when the strict CAS into audit_pending fails",async()=>{const receipts=repository();const original=receipts.transition;let failAuditPending=true;receipts.transition=vi.fn(async(action,key,from,to,result)=>{if(to==="audit_pending"&&failAuditPending){failAuditPending=false;throw new Error("strict CAS timeout")}return original(action,key,from,to,result)});const failed=vi.spyOn(receipts,"fail");const execute=vi.fn(async()=>({providerId:"once"}));const first=await executeDeploymentDispatch({action:"deployment.deploy",command:command(),principal,requestId:"one",repository:receipts,audit,execute});expect(first.commandStatus).toBe("audit_pending");expect(failed).not.toHaveBeenCalled();const replay=await executeDeploymentDispatch({action:"deployment.deploy",command:command(),principal,requestId:"two",repository:receipts,audit,execute});expect(replay.commandStatus).toBe("completed");expect(execute).toHaveBeenCalledOnce();});
});
