import { describe, expect, it, vi } from "vitest";
import { AuditPersistenceError, CommandConflictError, executeAdminCommand, type CommandReceipt, type CommandRepository } from "@/features/management/commands";
import { principalForActor } from "@/lib/auth/admin-capabilities";

function memoryRepository(): CommandRepository {
  const rows = new Map<string, CommandReceipt>();
  return {
    async begin(action, command, hash) { const key=`${action}:${command.idempotencyKey}`; const existing=rows.get(key); if(existing)return {created:false,receipt:existing}; const receipt={status:"accepted",request_hash:hash,result_reference:null,safe_error:null} as CommandReceipt;rows.set(key,receipt);return {created:true,receipt}; },
    async transition(action,key,from,to,result){const receipt=rows.get(`${action}:${key}`)!;if(!from.includes(receipt.status))throw new Error("invalid transition");rows.set(`${action}:${key}`,{...receipt,status:to,...(result===undefined?{}:{result_reference:result})});},
    async succeed(action,key,result){rows.set(`${action}:${key}`,{...(rows.get(`${action}:${key}`)!),status:"completed",result_reference:result});},
    async recordEffectResult(action,key,result){const value=rows.get(`${action}:${key}`)!;rows.set(`${action}:${key}`,{...value,result_reference:result,audit_context:{...(value.audit_context||{}),effectSucceeded:true}});},
    async fail(action,key,error){rows.set(`${action}:${key}`,{...(rows.get(`${action}:${key}`)!),status:"failed",safe_error:error});},
  };
}
const principal=principalForActor({actorId:"admin-1",actorType:"admin",role:"super_admin"});
const command=(overrides:Record<string,unknown>={})=>({targetId:"setting.batch",reason:"更新测试配置",idempotencyKey:"settings-key-001",payload:{replacements:{llm_model:"model-a"}},...overrides});

describe("management command executor",()=>{
   it("persists pending and succeeded audits then replays one canonical command",async()=>{const repository=memoryRepository();const execute=vi.fn(async()=>({changedKeys:["llm_model"]}));const actions:string[]=[];const audit=vi.fn(async(entry:{action:string})=>{actions.push(entry.action);return true});const first=await executeAdminCommand({action:"settings.replace",rawCommand:command(),principal,requestId:"req-1",repository,audit,execute});const second=await executeAdminCommand({action:"settings.replace",rawCommand:command(),principal,requestId:"req-2",repository,audit,execute});expect(first.replayed).toBe(false);expect(second).toMatchObject({replayed:true,result:{changedKeys:["llm_model"]}});expect(execute).toHaveBeenCalledTimes(1);expect(actions).toEqual(["settings.replace.requested","settings.replace.succeeded"]);});
  it("rejects an idempotency key reused for another payload",async()=>{const repository=memoryRepository();const audit=vi.fn(async()=>true);await executeAdminCommand({action:"settings.replace",rawCommand:command(),principal,requestId:null,repository,audit,execute:async()=>({ok:true})});await expect(executeAdminCommand({action:"settings.replace",rawCommand:command({payload:{replacements:{llm_model:"model-b"}}}),principal,requestId:null,repository,audit,execute:async()=>({ok:true})})).rejects.toBeInstanceOf(CommandConflictError);});
   it("returns a durable in-progress state for concurrent replay without repeating the effect",async()=>{const repository=memoryRepository();const audit=vi.fn(async()=>true);let release!:()=>void;const blocked=new Promise<void>(resolve=>{release=resolve;});const execute=vi.fn(async()=>{await blocked;return {ok:true};});const first=executeAdminCommand({action:"settings.replace",rawCommand:command(),principal,requestId:null,repository,audit,execute});await vi.waitFor(()=>expect(execute).toHaveBeenCalledTimes(1));const replay=await executeAdminCommand({action:"settings.replace",rawCommand:command(),principal,requestId:null,repository,audit,execute});expect(["accepted","effect_started"]).toContain(replay.commandStatus);expect(execute).toHaveBeenCalledTimes(1);release();await first;});
  it("fails closed for unknown targets and mismatched dangerous confirmation",async()=>{const repository=memoryRepository();const audit=vi.fn(async()=>true);await expect(executeAdminCommand({action:"x",rawCommand:command({targetId:"unknown.object"}),principal,requestId:null,repository,audit,execute:async()=>({})})).rejects.toThrow("未知");await expect(executeAdminCommand({action:"publish",rawCommand:command({targetId:"strategy.publish",confirmation:"wrong"}),principal,requestId:null,repository,audit,execute:async()=>({})})).rejects.toThrow("确认短语");});
   it("records a generic failed receipt without upstream details in audit",async()=>{const repository=memoryRepository();const audit=vi.fn(async()=>true);await expect(executeAdminCommand({action:"settings.replace",rawCommand:command(),principal,requestId:null,repository,audit,execute:async()=>{throw new Error("upstream schema token=secret");}})).rejects.toThrow("upstream");expect(audit).toHaveBeenCalledWith(expect.objectContaining({action:"settings.replace.failed",metadata:expect.objectContaining({errorCode:"COMMAND_EXECUTION_FAILED"})}));expect(JSON.stringify(audit.mock.calls)).not.toContain("upstream schema");});
  it("audits rejected commands before a receipt is created",async()=>{const repository=memoryRepository();const audit=vi.fn(async()=>true);await expect(executeAdminCommand({action:"settings.replace",rawCommand:command({targetId:"unknown.object"}),principal,requestId:"req-rejected",repository,audit,execute:async()=>({ok:true})})).rejects.toThrow("未知");expect(audit).toHaveBeenCalledWith(expect.objectContaining({action:"settings.replace.rejected",objectId:"unknown.object"}));});
  it.each([
    ["validation", null],
    ["capability", command({targetId:"unknown.object"})],
    ["confirmation", command({targetId:"strategy.publish",confirmation:"wrong"})],
  ])("fails closed when %s rejected audit returns false",async(_caseName,rawCommand)=>{const execute=vi.fn(async()=>({ok:true}));const operation=executeAdminCommand({action:"management.test",rawCommand,principal,requestId:"req-audit-false",repository:memoryRepository(),audit:vi.fn(async()=>false),execute});await expect(operation).rejects.toBeInstanceOf(AuditPersistenceError);await expect(operation).rejects.toMatchObject({status:503});expect(execute).not.toHaveBeenCalled();});
   it("fails closed when failed-outcome audit is unavailable and never repeats the side effect",async()=>{const repository=memoryRepository();const execute=vi.fn(async()=>{throw new Error("business failed")});const audit=vi.fn().mockResolvedValueOnce(true).mockResolvedValueOnce(false);const first=executeAdminCommand({action:"settings.replace",rawCommand:command(),principal,requestId:"req-failed-audit",repository,audit,execute});await expect(first).rejects.toBeInstanceOf(AuditPersistenceError);await expect(executeAdminCommand({action:"settings.replace",rawCommand:command(),principal,requestId:"req-replay",repository,audit:vi.fn(async()=>true),execute})).rejects.toThrow("管理命令执行失败");expect(execute).toHaveBeenCalledTimes(1);});
   it("has zero business side effects when pending audit storage fails",async()=>{const repository=memoryRepository();const execute=vi.fn(async()=>({changedKeys:["llm_model"]}));await expect(executeAdminCommand({action:"settings.replace",rawCommand:command(),principal,requestId:null,repository,audit:vi.fn(async()=>false),execute})).rejects.toBeInstanceOf(AuditPersistenceError);await expect(executeAdminCommand({action:"settings.replace",rawCommand:command(),principal,requestId:null,repository,audit:vi.fn(async()=>true),execute})).rejects.toThrow("审计服务暂时不可用");expect(execute).not.toHaveBeenCalled();});
  it.each(["backtest.start","backtest.cancel","backtest.resume"])("executes one side effect for repeated %s commands",async targetId=>{const repository=memoryRepository();const audit=vi.fn(async()=>true);const execute=vi.fn(async()=>({jobId:"job-1",log:["existing"],result:{processed:3}}));const raw={targetId,reason:"回测治理操作",idempotencyKey:`${targetId}:same-key`,payload:targetId==="backtest.start"?{startDate:"20260101",endDate:"20260101",maxMatches:5}:{jobId:"job-1"}};const first=await executeAdminCommand({action:"backtest.lifecycle",rawCommand:raw,principal,requestId:null,repository,audit,execute});const replay=await executeAdminCommand({action:"backtest.lifecycle",rawCommand:raw,principal,requestId:null,repository,audit,execute});expect(first.result).toMatchObject({jobId:"job-1",log:["existing"],result:{processed:3}});expect(replay).toMatchObject({replayed:true,result:{jobId:"job-1"}});expect(execute).toHaveBeenCalledTimes(1);});
});
