import { access, readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
const root=new URL("../",import.meta.url);const read=(p:string)=>readFile(new URL(p,root),"utf8");

describe("standalone release materialization and archive limits",()=>{
  it("materializes only trusted dependency links and rejects external, cyclic and dangling targets",async()=>{const s=await read("scripts/release-materialize.mjs");expect(s).toContain('path.join(workspaceReal, "node_modules")');expect(s).toContain("resolveSymlinkTarget");expect(s).toContain("Cyclic symlink rejected");expect(s).toContain("Dangling symlink rejected");expect(s).toContain("active = new Set");expect(s).toMatch(/escapes allowed dependency roots/);expect(s).toContain("copyFileStable");const runtime=await read("scripts/standalone-runtime-deps.mjs");expect(runtime).toContain("Empty standalone dependency link");expect(runtime).toContain("Dangling standalone dependency link");expect(runtime).toContain("Cyclic standalone dependency link");});
 it("requires all final tree nodes to be regular files or directories with single-link files",async()=>{const materialize=await read("scripts/release-materialize.mjs"),archive=await read("scripts/release-archive.py"),verify=await read("scripts/verify-release.sh");expect(materialize).toContain("Materialized stage contains a link, special file, or hard link");expect(materialize).toContain("info.nlink !== 1");expect(archive).toContain("Stage contains link, special file, or hard link");expect(archive).toContain("st_nlink != 1");expect(verify).toContain("Release tree contains a link or special file");});
 it("forbids environment, source-control, cache and QA material",async()=>{const limits=JSON.parse(await read("scripts/release-limits.json"));for(const value of [".git",".cache","coverage","test-results","playwright-report","blob-report"]){expect(limits.forbiddenSegments).toContain(value)}expect(limits.forbiddenBasenamePatterns.join(" ")).toContain("env");expect(limits.forbiddenPathPatterns.join(" ")).toContain(".next/(?:cache|dev|diagnostics)");});
  it("isolates root environment files with unconditional restoration and rejects standalone leakage",async()=>{const build=await read("scripts/build.sh"),create=await read("scripts/create-release.sh");expect(build).toContain("trap on_exit EXIT");expect(build).toContain("trap 'exit 129' HUP");expect(build).toContain("trap 'exit 130' INT");expect(build).toContain("trap 'exit 143' TERM");expect(build).toContain('mktemp -d "$workspace_parent/.peilv-build-env.XXXXXX"');expect(build).toMatch(/mv -- "\$path" "\$env_vault\/\$name"/);expect(build).toMatch(/mv -- "\$env_vault\/\$name" "\$COZE_WORKSPACE_PATH\/\$name"/);expect(build.match(/find \.next\/standalone -name '\.env\*'/g)).toHaveLength(2);expect(create).toContain("Standalone contains a forbidden environment file");});
 it("removes only unreferenced static source maps and rejects maps in the assembled runtime",async()=>{const build=await read("scripts/build.sh");expect(build).toMatch(/grep -RIlF --include='\*\.js' --include='\*\.css' -- "\$map_name" \.next\/static/);expect(build).toContain('rm -- "$source_map"');expect(build).toContain("assembled standalone contains a source map");});
 it("binds every final regular file to the release manifest hash set",async()=>{const create=await read("scripts/create-release.sh"),verify=await read("scripts/verify-release.sh");expect(create).toMatch(/walk\(stageDir\)[\s\S]{0,700}sha256/);expect(verify).toMatch(/walk\(root\)[\s\S]{0,900}Release file tree hash mismatch/);expect(verify).toMatch(/JSON\.stringify\(actual\)!==JSON\.stringify\(declared\)/);});
 it("binds migration filenames to versions and content hashes without requiring SQL body markers",async()=>{const verify=await read("scripts/verify-release.sh");expect(verify).toContain('m.file!==`${m.version}.sql`');expect(verify).toMatch(/createHash\("sha256"\)[\s\S]{0,120}m\.sha256/);expect(verify).not.toContain("content.toString(\"utf8\").includes");});
 it("rejects unsafe names, PAX metadata, links and special entries",async()=>{const a=await read("scripts/release-archive.py");expect(a).toMatch(/ord\(c\) < 0x21/);expect(a).toContain("PAX archive metadata rejected");expect(a).toMatch(/member\.islnk\(\).*member\.issym\(\)/);expect(a).toContain("Archive contains a link or special file");});
 it("enforces member, file, total, path, archive and compression limits before extraction",async()=>{const a=await read("scripts/release-archive.py"),limits=JSON.parse(await read("scripts/release-limits.json"));for(const key of ["maxArchiveBytes","maxMembers","maxFileBytes","maxTotalBytes","maxPathBytes","maxPathDepth","maxCompressionRatio"]){expect(limits[key],key).toBeGreaterThan(0)}for(const key of ["maxArchiveBytes","maxMembers","maxFileBytes","maxTotalBytes","maxPathDepth","maxCompressionRatio"]){expect(a,key).toContain(`LIMITS["${key}"]`)}const extract=a.slice(a.indexOf("def extract_file"),a.indexOf("def extract(archive"));expect(extract).toMatch(/inspect_file\(fileobj,size\)[\s\S]{0,400}tarfile\.open\(fileobj=fileobj, mode=["']r:gz["']\)/);});
 it("copies source archives with same-FD before/after stat and partial-write loops",async()=>{const helper=await read("scripts/private-copy.mjs");expect(helper).toContain("fs.fstatSync(input)");expect(helper.match(/fs\.fstatSync\(input\)/g)).toHaveLength(2);for(const key of ["dev","ino","size","ctimeMs","mtimeMs","mode","nlink"]){expect(helper).toContain(key)}expect(helper).toMatch(/while \(written < count\)/);expect(helper).toMatch(/writeSync\(output, buffer, written, count - written/);expect(helper).toContain("fs.fsyncSync(output)");});
 it("uses one host TCB helper for the exact trusted verifier set",async()=>{const helper=await read("scripts/lib/trusted-release-verifier.sh");for(const file of ["verify-release.sh","release-archive.py","release-limits.json","private-copy.mjs","candidate-stage.sh","candidate-lifecycle.sh","deployment-budget.sh","openresty-control"])expect(helper).toContain(file);expect(helper).toContain('${#seen[@]} == 8');for(const name of ["deploy-production.sh","production-preflight.sh","rollback-production.sh"]){const s=await read(`scripts/${name}`);expect(s).toContain("trusted-release-verifier.sha256");expect(s).toContain('"$trusted_verifier_helper" "$trusted_verifier_sha_file" /usr/local/libexec/peilv');}const create=await read("scripts/create-release.sh");expect(create).not.toContain("trusted-release-verifier.sha256");});

  it("assembles and resolves the explicit Next runtime dependency closure",async()=>{const build=await read("scripts/build.sh"),runtime=await read("scripts/standalone-runtime-deps.mjs");expect(build).toContain("standalone-runtime-deps.mjs");expect(runtime).toContain('["next", "styled-jsx", "react", "react-dom"]');expect(runtime).toContain("release-materialize.mjs");expect(runtime).toContain("dependencyRoot");expect(build).toContain('runtimeRequire.resolve(`${name}/package.json`)');});
  it("serializes workspace builds and safely removes only the exact standalone output",async()=>{const build=await read("scripts/build.sh");expect(build).toContain('mkdir -- "$build_lock"');expect(build).toContain('workspace_real="$(cd "$COZE_WORKSPACE_PATH" && pwd -P)"');expect(build).toContain('workspace_parent="$(cd "$workspace_real/.." && pwd -P)"');expect(build).toContain('standalone_real="$(realpath "$standalone_dir")"');expect(build).toContain('[[ "$standalone_real" == "$expected_real" ]]');expect(build).toContain('rm -rf -- "$standalone_dir"');expect(build).toContain("validate_lock_node");expect(build).toContain("build_lock_token");expect(build).toContain("heartbeat_build_lock");expect(build).toContain("PEILV_BUILD_LOCK_MAX_WAIT_SECONDS");expect(build).toContain("trap on_exit EXIT");expect(build).not.toMatch(/rm\s+-rf\s+--\s+\.next/);});
  it("excludes local delivery evidence from tracing and rejects any final standalone pollution",async()=>{const config=await read("next.config.ts"),build=await read("scripts/build.sh");for(const value of ["release-artifacts","test-results","playwright-report","blob-report","coverage",".test-tmp",".claude",".trellis"]){expect(config).toContain(value)}expect(config).toContain("outputFileTracingExcludes");expect(build).toContain("assembled standalone contains local-only path");expect(build).toContain("assembled standalone contains a local test path");expect(build.indexOf("assembled standalone contains local-only path")).toBeLessThan(build.indexOf("Build completed successfully!"));});
  it("keeps Inspector tooling outside production source and dependency closure",async()=>{const layout=await read("src/app/layout.tsx"),pkgText=await read("package.json"),lock=await read("pnpm-lock.yaml"),pkg=JSON.parse(pkgText);expect(layout).not.toContain("react-dev-inspector");expect(layout).not.toContain("<Inspector");await expect(access(new URL(".babelrc",root))).rejects.toThrow();for(const name of ["react-dev-inspector","react-dev-utils","shell-quote"]){expect(pkgText).not.toContain(name);expect(lock).not.toContain(name);}expect(pkg.devDependencies?.["@react-dev-inspector/babel-plugin"]).toBeUndefined();expect(pkg.devDependencies?.["@react-dev-inspector/middleware"]).toBeUndefined();});

 it("excludes exact root operational paths on both creation and verification",async()=>{const create=await read("scripts/create-release.sh"),verify=await read("scripts/verify-release.sh");for(const name of ["rotate-internal-secret.sh","deploy-production.sh","production-preflight.sh","rollback-production.sh"]){expect(create).toContain(name);expect(verify).toContain(name);}expect(create).not.toMatch(/cp[^\n]*rotate-internal-secret\.sh/);expect(verify).toContain('for path in "${forbidden_release_paths[@]}"');});
 it("allowlists only the administrator bootstrap CLI and migration runner and verifies their syntax",async()=>{const create=await read("scripts/create-release.sh"),verify=await read("scripts/verify-release.sh");for(const value of [create,verify]){expect(value).toContain("allowed_release_script_paths=(scripts/admin-bootstrap.mjs scripts/run-migrations.mjs)");expect(value).toContain("scripts/admin-bootstrap.mjs");expect(value).toContain("scripts/run-migrations.mjs");expect(value).toContain("node --check");}expect(create).not.toMatch(/cp\s+-[a-zA-Z]*r[^\n]*scripts|cp[^\n]*scripts\/\s/);expect(verify).toContain('packageJson?.scripts?.["admin:bootstrap"]!=="node ./scripts/admin-bootstrap.mjs"');});
});
