import { describe,expect,it,vi } from "vitest";
import { ADMIN_QUERY_CONTRACT_VERSION } from "@/features/strategy-lab/admin-query-contracts";
import { AdminQueryCursorError,adminQueryFilterHash,createAdminQueryCursorCodec } from "@/features/strategy-lab/admin-query-cursor";
import { StrategyLabAdminQueryService } from "@/features/strategy-lab/admin-query-service";
import type { StrategyLabAdminQueryRepository } from "@/features/strategy-lab/admin-query-repository";

const id="10000000-0000-4000-8000-000000000001";
function repository():StrategyLabAdminQueryRepository{return {listRuns:vi.fn(async()=>[{id,runType:"shadow",status:"running" as const,datasetMode:"strict_asof",startDate:"20260701",endDate:"20260701",datasetCutoffAt:"2026-07-01T04:00:00.000Z",createdAt:"2026-07-01T04:01:00.000Z",updatedAt:"2026-07-01T04:01:00.000Z",coverage:{predictions:12,matches:1,settled:2},auditStatus:"audit_pending" as const}]),runOverview:vi.fn(async()=>({id})),runMatrix:vi.fn(async()=>Array.from({length:12},(_,i)=>({strategy:["A","B","C","D"][Math.floor(i/3)] as "A",checkpoint:["T1215","T30","T03"][i%3] as "T1215",executable:i<9,compatibilityOnly:i>=9,sample:0,decisions:{recommend:0,observe:0,reanalyze:0,insufficient:0},fallback:0,snapshotQuality:{ready:0,partial:0,insufficient:0,invalid:0,missing:0},actual:{counted:0,unavailable:0,outcomes:{win:0,halfWin:0,push:0,halfLoss:0,loss:0},profitMicros:"0",stakeMicros:"0",roi:null},theoretical:{counted:0,unavailable:0,outcomes:{win:0,halfWin:0,push:0,halfLoss:0,loss:0},profitMicros:"0",stakeMicros:"0",roi:null}}))),runReport:vi.fn(async()=>({validSample:0})),listSnapshots:vi.fn(async()=>[]),listPredictions:vi.fn(async()=>[]),listSettlements:vi.fn(async()=>[]),settlementChain:vi.fn(async()=>({id})),runAudit:vi.fn(async()=>[])};}
describe("Strategy Lab signed admin query",()=>{it("signs opaque canonical cursor and rejects tampering",()=>{const codec=createAdminQueryCursorCodec("a".repeat(32));const payload={contractVersion:ADMIN_QUERY_CONTRACT_VERSION,sort:"created_desc" as const,lastCreatedAt:"2026-07-01T00:00:00.000Z",lastId:id,filterHash:adminQueryFilterHash({status:"running"})};const encoded=codec.encode(payload);expect(encoded).not.toContain(id);expect(codec.decode(encoded)).toEqual(payload);expect(()=>codec.decode(`${encoded.slice(0,-1)}x`)).toThrow(AdminQueryCursorError);});
it("rejects a cursor after filters change",async()=>{const codec=createAdminQueryCursorCodec("b".repeat(32));const repo=repository();const service=new StrategyLabAdminQueryService(repo,codec,()=>new Date("2026-07-18T00:00:00Z"));const oldFilters={collection:"runs",status:"running",sort:"created_desc" as const};const cursor=codec.encode({contractVersion:ADMIN_QUERY_CONTRACT_VERSION,sort:"created_desc",lastCreatedAt:"2026-07-01T00:00:00.000Z",lastId:id,filterHash:adminQueryFilterHash(oldFilters)});await expect(service.runs({requestId:"r1",filters:{status:"failed",sort:"created_desc"},limit:50,cursor})).rejects.toMatchObject({reason:"filter_mismatch"});});
it("returns immutable 12-cell matrix with null empty ROI",async()=>{const service=new StrategyLabAdminQueryService(repository(),createAdminQueryCursorCodec("c".repeat(32)));const result=await service.matrix("request-1",id);expect(result.data).toHaveLength(12);expect(result.data[0].actual.roi).toBeNull();expect(Object.isFrozen(result.data)).toBe(true);expect(result.contractVersion).toBe("read-v1");});});
