import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { PostgresStrategyLabAdminQueryRepository } from "@/features/strategy-lab/postgres-admin-query-repository";
import type { QuerySqlClient,QuerySqlExecutor } from "@/features/strategy-lab/admin-query-repository";

const root=new URL("..",import.meta.url),read=(path:string)=>readFile(new URL(path,root),"utf8");
const uuid=(n:number)=>`20000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const hash=(char:string)=>char.repeat(64);
const runId=uuid(1),captureId=uuid(2),policyHash=hash("a");
class Client implements QuerySqlClient{readonly calls:{sql:string;parameters:readonly unknown[]}[]=[];constructor(readonly db:PGlite){}async query<Row extends Record<string,unknown>>(sql:string,parameters:readonly unknown[]=[]){this.calls.push({sql,parameters});const result=await this.db.query<Row>(sql,[...parameters]);return{rows:result.rows}}async transaction<T>(callback:(tx:QuerySqlExecutor)=>Promise<T>,options:{readOnly:true;isolationLevel:"repeatable read"}){expect(options).toEqual({readOnly:true,isolationLevel:"repeatable read"});return this.db.transaction(async transaction=>callback({query:async<Row extends Record<string,unknown>>(sql:string,parameters:readonly unknown[]=[])=>{this.calls.push({sql,parameters});const result=await transaction.query<Row>(sql,[...parameters]);return{rows:result.rows}}}))}}
let db:PGlite,client:Client,repository:PostgresStrategyLabAdminQueryRepository;

beforeAll(async()=>{db=new PGlite();await db.exec(`CREATE TABLE schema_migrations(version VARCHAR(100) PRIMARY KEY,description TEXT NOT NULL);CREATE TABLE odds_snapshots(id SERIAL PRIMARY KEY,match_id VARCHAR(20) NOT NULL,match_date VARCHAR(8) NOT NULL,company_id VARCHAR(20) NOT NULL,market_type TEXT NOT NULL,snapshot_type TEXT NOT NULL,source TEXT NOT NULL,odds JSONB NOT NULL,source_observed_at TIMESTAMPTZ,collected_at TIMESTAMPTZ NOT NULL,content_hash TEXT NOT NULL,idempotency_key TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE strategy_versions(version TEXT PRIMARY KEY);CREATE TABLE prediction_results(id SERIAL PRIMARY KEY);CREATE TABLE match_results(id SERIAL PRIMARY KEY,match_id VARCHAR(20) NOT NULL,match_date VARCHAR(8) NOT NULL,status TEXT NOT NULL DEFAULT 'finished',home_score INTEGER,away_score INTEGER,score_source TEXT NOT NULL DEFAULT 'official',observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),settled_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);for(const migration of ["0020_strategy_lab_fact_model.sql","0021_strategy_lab_policy_and_artifacts.sql","0022_strategy_lab_snapshot_provider.sql","0023_strategy_lab_trusted_settlement.sql"])await db.exec(await read(`migrations/${migration}`));
await db.exec(`INSERT INTO strategy_versions(version) VALUES('A-v1'),('B-v1'),('C-v1'),('D-v1');INSERT INTO strategy_lab_league_policy_artifacts(content_hash,version_hash,mode,leagues,canonical_payload,source_row_count,schema_version) VALUES('${policyHash}','${policyHash}','user_focused_leagues','["League"]',jsonb_build_object('schemaVersion',1,'mode','user_focused_leagues','leagues','["League"]'::jsonb),1,1);INSERT INTO strategy_lab_league_policy_captures(id,artifact_hash,dataset_cutoff_at,captured_at,source_history_cutoff,evidence_hash,created_by,trace_id) VALUES('${captureId}','${policyHash}','2026-07-17T12:15Z','2026-07-17T12:16Z','2026-07-17T12:15Z','${hash("b")}','fixture','trace');INSERT INTO strategy_lab_experiment_runs(id,run_type,status,dataset_mode,start_date,end_date,dataset_cutoff_at,strategy_versions,configuration,code_version,idempotency_key,created_by,trace_id,created_at,updated_at) VALUES('${runId}','shadow','pending','strict_asof','20260717','20260717','2026-07-17T12:15Z','{"A":"A-v1","B":"B-v1","C":"C-v1","D":"D-v1"}',jsonb_build_object('policy',jsonb_build_object('captureId','${captureId}')),'v','run','fixture','trace','2026-07-17T09:00Z','2026-07-17T09:00Z');UPDATE strategy_lab_experiment_runs SET status='running',started_at='2026-07-17T10:00Z',updated_at='2026-07-17T10:00Z' WHERE id='${runId}';
INSERT INTO strategy_lab_match_facts(id,match_id,match_date,league_name_raw,league_name_normalized,kickoff_at,source,source_observed_at,dataset_cutoff_at,canonical_payload,content_hash,revision,schema_version,trace_id) VALUES('${uuid(10)}','m-in','20260717','League','League','2026-07-17T16:00Z','fixture','2026-07-17T09:00Z','2026-07-17T12:15Z',jsonb_build_object('schemaVersion',1,'matchId','m-in','matchDate','20260717','league','League','kickoffAt','2026-07-17T16:00Z'::timestamptz,'source','fixture','sourceObservedAt','2026-07-17T09:00Z'::timestamptz,'datasetCutoffAt','2026-07-17T12:15Z'::timestamptz,'revision',1),'${hash("c")}',1,1,'trace'),('${uuid(11)}','m-out','20260717','Other','Other','2026-07-17T16:00Z','fixture','2026-07-17T09:00Z','2026-07-17T12:15Z',jsonb_build_object('schemaVersion',1,'matchId','m-out','matchDate','20260717','league','Other','kickoffAt','2026-07-17T16:00Z'::timestamptz,'source','fixture','sourceObservedAt','2026-07-17T09:00Z'::timestamptz,'datasetCutoffAt','2026-07-17T12:15Z'::timestamptz,'revision',1),'${hash("d")}',1,1,'trace');
INSERT INTO odds_snapshots(match_id,match_date,company_id,market_type,snapshot_type,source,odds,source_observed_at,collected_at,content_hash,idempotency_key,hash_version,canonical_content_hash) VALUES('m-in','20260717','3','asian_handicap','crown12','fixture','{}','2026-07-17T11:00Z','2026-07-17T11:01Z','${hash("e")}','odds','canonical-json-v2','${hash("e")}');INSERT INTO match_results(match_id,match_date,status,home_score,away_score,settled_at) VALUES('m-in','20260717','finished',1,0,'2026-07-17T18:00Z'),('m-out','20260717','finished',1,0,'2026-07-17T18:00Z');`);
for(let index=0;index<7;index++){const strategy=["A","B","C","D","A","B","A"][index],executed=index===2?"A":strategy,match=index===6?"m-out":"m-in",checkpoint=["T1215","T30","T03"][index%3],source=strategy==="D"?"d_compat_shadow":"experiment",status=index===5?"observe":"recommend",base=500+index*3,snapshot=checkpoint==="T1215"?uuid(base):checkpoint==="T30"?uuid(base+1):uuid(base+2),prediction=uuid(200+index),suffix=String(index).padStart(2,"0");const set=(id:string,type:string,time:string,previous:string|null)=>`INSERT INTO strategy_lab_snapshot_sets(id,run_id,match_id,match_date,checkpoint_type,checkpoint_at,dataset_mode,status,previous_snapshot_set_id,revision,source_cutoff_at,content_hash,schema_version,completeness,trace_id,created_at) VALUES('${id}','${runId}','${match}','20260717','${type}','${time}','strict_asof','missing',${previous?`'${previous}'`:'NULL'},1,'${time}','snap-${id}',1,'{"reasonCode":"NO_EVIDENCE"}','trace','2026-07-17T${String(10+index).padStart(2,"0")}:00Z');`;let snapshots=set(uuid(base),"T1215",`2026-07-17T12:00:${suffix}Z`,null);if(checkpoint!=="T1215")snapshots+=set(uuid(base+1),"T30",`2026-07-17T12:10:${suffix}Z`,uuid(base));if(checkpoint==="T03")snapshots+=set(uuid(base+2),"T03",`2026-07-17T12:15:${suffix}Z`,uuid(base+1));await db.exec(`${snapshots}INSERT INTO strategy_lab_predictions(id,run_id,match_id,match_date,checkpoint_type,snapshot_set_id,requested_strategy,executed_strategy,strategy_version,decision_status,selection,locked_deterministic,reason_code,branch_id,input_hash,output_hash,decision_payload,fallback_reason,source,idempotency_key,trace_id,created_at) VALUES('${prediction}','${runId}','${match}','20260717','${checkpoint}','${snapshot}','${strategy}','${executed}','${executed}-v1','${status}',${status==="recommend"?"'home'":"NULL"},true,'R','B','input-${index}','output-${index}','{}',${index===2?"'C unavailable'":"NULL"},'${source}','p-${index}','trace','2026-07-17T${String(10+index).padStart(2,"0")}:30Z');`)}
await db.exec(`INSERT INTO strategy_lab_settlements(id,prediction_id,revision,match_result_id,actual_quote_snapshot_id,quote_basis,outcome,profit_units,is_counted,settlement_basis,evidence,settled_at,settled_by,trace_id,created_at) VALUES('${uuid(300)}','${uuid(200)}',1,1,1,'actual','loss',-1,true,'actual_quote','{}','2026-07-17T18:00Z','fixture','trace','2026-07-17T18:00Z');INSERT INTO strategy_lab_settlements(id,prediction_id,revision,match_result_id,actual_quote_snapshot_id,quote_basis,outcome,profit_units,is_counted,settlement_basis,evidence,settled_at,settled_by,supersedes,trace_id,created_at) VALUES('${uuid(301)}','${uuid(200)}',2,1,1,'actual','win',0.333333,true,'actual_quote','{}','2026-07-17T19:00Z','fixture','${uuid(300)}','trace','2026-07-17T19:00Z');`);
await db.exec(`INSERT INTO strategy_lab_settlements(id,prediction_id,revision,match_result_id,quote_basis,outcome,profit_units,is_counted,settlement_basis,evidence,settled_at,settled_by,trace_id,created_at) VALUES('${uuid(302)}','${uuid(201)}',1,1,'theoretical','half_win',0.5,true,'theoretical_quote','{"theoreticalQuote":{"line":"0.5"}}','2026-07-17T18:00Z','fixture','trace','2026-07-17T18:01Z'),('${uuid(303)}','${uuid(202)}',1,1,'theoretical','unavailable',NULL,false,'theoretical_quote','{"theoreticalQuote":{"line":"0.5"}}','2026-07-17T18:00Z','fixture','trace','2026-07-17T18:02Z');INSERT INTO strategy_lab_command_receipts(id,action,operation_key,payload_hash,status,result_type,result_id,actor_id,request_id,created_at,updated_at) VALUES('${uuid(400)}','run.create','secret-operation-key-123456','${hash("f")}','audit_pending','strategy_lab_run','${runId}','private-actor','request-private','2026-07-17T20:00Z','2026-07-17T20:00Z');`);
client=new Client(db);repository=new PostgresStrategyLabAdminQueryRepository(client);},60_000);
afterAll(async()=>db.close());

describe("Strategy Lab admin query on migrated PGlite",()=>{
 it("filters by frozen policy and returns exact server aggregates",async()=>{const matrix=await repository.runMatrix(runId),report=await repository.runReport(runId);expect(matrix).toHaveLength(12);expect(matrix?.find(cell=>cell.strategy==="C"&&cell.checkpoint==="T03")?.fallback).toBe(1);expect(matrix?.find(cell=>cell.strategy==="D")?.executable).toBe(false);expect(report).toMatchObject({validSample:6,cFallback:1,dBaseline:1,actual:{counted:1,unavailable:0,profitMicros:"333333",stakeMicros:"1000000"},theoretical:{counted:1,unavailable:1,profitMicros:"500000",stakeMicros:"1000000"}});expect((report as {actual:{roi:string}}).actual.roi).toMatch(/^0\.333333/);expect((report as {theoretical:{roi:string}}).theoretical.roi).toMatch(/^0\.5/);});
 it("paginates by stable tuple without duplicates or omissions",async()=>{const first=await repository.listPredictions({filters:{runId,sort:"created_desc"},limit:3});const tail=first.at(-1)!;const second=await repository.listPredictions({filters:{runId,sort:"created_desc"},limit:4,cursor:{contractVersion:"read-v1",sort:"created_desc",lastCreatedAt:tail.createdAt,lastId:tail.id,filterHash:hash("0")}});expect(first).toHaveLength(3);expect(second).toHaveLength(4);expect(new Set([...first,...second].map(row=>row.id)).size).toBe(7);});
 it("uses latest settlement by default and preserves history pagination",async()=>{const latest=await repository.listSettlements({filters:{runId,sort:"created_desc",history:false},limit:20});const history=await repository.listSettlements({filters:{runId,sort:"created_desc",history:true},limit:20});expect(latest.filter(row=>row.predictionId===uuid(200))).toHaveLength(1);expect(latest.find(row=>row.predictionId===uuid(200))?.revision).toBe(2);expect(history.filter(row=>row.predictionId===uuid(200))).toHaveLength(2);});
 it("validates continuous chain and masks audit secrets",async()=>{const chain=await repository.settlementChain(uuid(200));expect((chain as {revisions:{current:boolean;superseded:boolean}[]}).revisions).toMatchObject([{current:false,superseded:true},{current:true,superseded:false}]);const audit=await repository.runAudit({filters:{runId,sort:"created_desc"},limit:10});expect(JSON.stringify(audit)).not.toContain("secret-operation-key-123456");expect(JSON.stringify(audit)).not.toContain("private-actor");expect(audit?.[0]).toMatchObject({status:"audit_pending",operationKeyMasked:"secret-o…3456",actorId:"pr***or"});});
 it("is parameterized, bounded in query count, read-only, and zero-write",async()=>{const before=(await db.query<{count:number}>("SELECT count(*)::int count FROM strategy_lab_predictions")).rows[0].count;client.calls.length=0;await repository.runReport(runId);expect(client.calls).toHaveLength(2);expect(client.calls.every(call=>call.parameters.includes(runId))).toBe(true);expect(client.calls.every(call=>!/^\s*(insert|update|delete)/i.test(call.sql))).toBe(true);const after=(await db.query<{count:number}>("SELECT count(*)::int count FROM strategy_lab_predictions")).rows[0].count;expect(after).toBe(before);});
});
