import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { afterEach, describe, expect, it } from "vitest";

const root=new URL("..",import.meta.url);const read=(path:string)=>readFile(new URL(path,root),"utf8");
const uuid=(n:number)=>`22000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const hash="a".repeat(64);const databases:PGlite[]=[];
async function base(){const db=new PGlite();databases.push(db);await db.exec(`CREATE TABLE schema_migrations(version VARCHAR(100) PRIMARY KEY,description TEXT NOT NULL);CREATE TABLE user_focused_leagues(id SERIAL PRIMARY KEY,league_name TEXT NOT NULL UNIQUE);CREATE TABLE odds_snapshots(id SERIAL PRIMARY KEY,match_id VARCHAR(20) NOT NULL,match_date VARCHAR(8) NOT NULL,company_id VARCHAR(20) NOT NULL,market_type TEXT NOT NULL,snapshot_type TEXT NOT NULL,source TEXT NOT NULL,odds JSONB NOT NULL,source_observed_at TIMESTAMPTZ,collected_at TIMESTAMPTZ NOT NULL,content_hash TEXT NOT NULL,idempotency_key TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE strategy_versions(version TEXT PRIMARY KEY);CREATE TABLE prediction_results(id SERIAL PRIMARY KEY);CREATE TABLE match_results(id SERIAL PRIMARY KEY,match_id VARCHAR(20) NOT NULL,match_date VARCHAR(8) NOT NULL);`);await db.exec(await read("migrations/0020_strategy_lab_fact_model.sql"));await db.exec(await read("migrations/0021_strategy_lab_policy_and_artifacts.sql"));return db;}
async function migrated(){const db=await base();await db.exec(await read("migrations/0022_strategy_lab_snapshot_provider.sql"));return db;}
async function seedSet(db:PGlite,id:string,status:string){const completeness=status==="ready"||status==="partial"?"{}":'{"reasonCode":"NO_EVIDENCE"}';await db.exec(`INSERT INTO strategy_lab_experiment_runs(id,run_type,status,dataset_mode,start_date,end_date,dataset_cutoff_at,strategy_versions,configuration,code_version,idempotency_key,created_by,trace_id) VALUES('${uuid(1)}','shadow','pending','strict_asof','20260717','20260717','2026-07-17T15:00Z','{}','{}','v','run','a','t') ON CONFLICT DO NOTHING;INSERT INTO strategy_lab_snapshot_sets(id,run_id,match_id,match_date,checkpoint_type,checkpoint_at,dataset_mode,status,revision,source_cutoff_at,content_hash,schema_version,completeness,trace_id) VALUES('${id}','${uuid(1)}','m','20260717','T1215','2026-07-17T04:15Z','strict_asof','${status}',1,'2026-07-17T04:15Z','h',2,'${completeness}','t');`);}
afterEach(async()=>{await Promise.all(databases.splice(0).map(db=>db.close()));});

describe("0022 Strategy Lab snapshot provider migration",()=>{
 it("applies the exact 0020 -> 0021 -> 0022 chain and registers all versions",async()=>{const db=await migrated();const r=await db.query<{version:string}>("SELECT version FROM schema_migrations WHERE version LIKE '002%' ORDER BY version");expect(r.rows.map(x=>x.version)).toEqual(["0020_strategy_lab_fact_model","0021_strategy_lab_policy_and_artifacts","0022_strategy_lab_snapshot_provider"]);});
 it("backfills legacy rows with the v1 default and null canonical hash",async()=>{const db=await base();await db.exec(`INSERT INTO odds_snapshots(match_id,match_date,company_id,market_type,snapshot_type,source,odds,collected_at,content_hash,idempotency_key) VALUES('m','20260717','3','asian_handicap','crown12','x','{}',NOW(),'legacy','legacy')`);await db.exec(await read("migrations/0022_strategy_lab_snapshot_provider.sql"));const r=await db.query<{hash_version:string;canonical_content_hash:string|null}>("SELECT hash_version,canonical_content_hash FROM odds_snapshots");expect(r.rows[0]).toEqual({hash_version:"legacy-json-v1",canonical_content_hash:null});});
 it("accepts a legal canonical v2 row",async()=>{const db=await migrated();await expect(db.exec(`INSERT INTO odds_snapshots(match_id,match_date,company_id,market_type,snapshot_type,source,odds,collected_at,content_hash,idempotency_key,hash_version,canonical_content_hash) VALUES('m','20260717','3','asian_handicap','crown12','x','{}',NOW(),'${hash}','v2','canonical-json-v2','${hash}')`)).resolves.toBeDefined();});
 it.each([["unknown version","future-v3",hash],["v1 canonical","legacy-json-v1",hash],["v2 empty","canonical-json-v2",null],["v2 non64","canonical-json-v2","abc"],["v2 unequal","canonical-json-v2","b".repeat(64)]])("rejects %s hash contract",async(_label,version,canonical)=>{const db=await migrated();await expect(db.query(`INSERT INTO odds_snapshots(match_id,match_date,company_id,market_type,snapshot_type,source,odds,collected_at,content_hash,idempotency_key,hash_version,canonical_content_hash) VALUES('m','20260717','3','asian_handicap','crown12','x','{}',NOW(),$1,$2,$3,$4)`,[hash,String(_label),version,canonical])).rejects.toThrow();});
 it("rejects strict item v1 and accepts strict item v2",async()=>{const db=await migrated();await db.exec("BEGIN");await seedSet(db,uuid(2),"ready");await db.exec(`INSERT INTO odds_snapshots(match_id,match_date,company_id,market_type,snapshot_type,source,odds,source_observed_at,collected_at,content_hash,idempotency_key) VALUES('m','20260717','3','asian_handicap','crown12','x','{}','2026-07-17T04:15Z','2026-07-17T04:15Z','legacy','v1')`);await expect(db.exec(`INSERT INTO strategy_lab_snapshot_items SELECT '${uuid(2)}',id,'current','3','asian_handicap','crown12','2026-07-17T04:15Z','2026-07-17T04:15Z',NOW() FROM odds_snapshots WHERE idempotency_key='v1'`)).rejects.toThrow();await db.exec("ROLLBACK;BEGIN");await seedSet(db,uuid(2),"ready");await db.exec(`INSERT INTO odds_snapshots(match_id,match_date,company_id,market_type,snapshot_type,source,odds,source_observed_at,collected_at,content_hash,idempotency_key,hash_version,canonical_content_hash) VALUES('m','20260717','3','asian_handicap','crown12','x','{}','2026-07-17T04:15Z','2026-07-17T04:15Z','${hash}','v2','canonical-json-v2','${hash}')`);await db.exec(`INSERT INTO strategy_lab_snapshot_items SELECT '${uuid(2)}',id,'current','3','asian_handicap','crown12','2026-07-17T04:15Z','2026-07-17T04:15Z',NOW() FROM odds_snapshots WHERE idempotency_key='v2'`);await expect(db.exec("COMMIT")).resolves.toBeDefined();});
 it("enforces current-only role, one item per set, and status cardinality",async()=>{const db=await migrated();await db.exec("BEGIN");await seedSet(db,uuid(3),"ready");await expect(db.exec(`INSERT INTO strategy_lab_snapshot_items VALUES('${uuid(3)}',1,'previous','3','asian_handicap','crown12',NOW(),NOW(),NOW())`)).rejects.toThrow();await db.exec("ROLLBACK;BEGIN");await seedSet(db,uuid(4),"ready");await expect(db.exec("COMMIT")).rejects.toThrow();});
 it("rejects odds snapshot update and delete",async()=>{const db=await migrated();await db.exec(`INSERT INTO odds_snapshots(match_id,match_date,company_id,market_type,snapshot_type,source,odds,collected_at,content_hash,idempotency_key) VALUES('m','20260717','3','asian_handicap','crown12','x','{}',NOW(),'legacy','immutable')`);await expect(db.exec("UPDATE odds_snapshots SET source='y'")).rejects.toThrow();await expect(db.exec("DELETE FROM odds_snapshots")).rejects.toThrow();});
 it.each(["role","duplicate","cardinality"])("fails dirty preflight independently: %s",async kind=>{const db=await base();await db.exec("ALTER TABLE strategy_lab_snapshot_items DISABLE TRIGGER ALL; ALTER TABLE strategy_lab_snapshot_sets DISABLE TRIGGER ALL");await seedSet(db,uuid(10),kind==="cardinality"?"ready":"missing");if(kind!=="cardinality"){await db.exec(`INSERT INTO odds_snapshots(match_id,match_date,company_id,market_type,snapshot_type,source,odds,collected_at,content_hash,idempotency_key) VALUES('m','20260717','3','asian_handicap','crown12','x','{}',NOW(),'x','a'),('m','20260717','3','asian_handicap','crown12','x','{}',NOW(),'x','b');INSERT INTO strategy_lab_snapshot_items VALUES('${uuid(10)}',1,'${kind==="role"?"previous":"current"}','3','asian_handicap','crown12',NOW(),NOW(),NOW());${kind==="duplicate"?`INSERT INTO strategy_lab_snapshot_items VALUES('${uuid(10)}',2,'current','3','asian_handicap','crown12',NOW(),NOW(),NOW());`:""}`);}await expect(db.exec(await read("migrations/0022_strategy_lab_snapshot_provider.sql"))).rejects.toThrow(/0022 preflight failed/);});
 it("creates hardened functions, indexes, deferred triggers, RLS/FORCE and PUBLIC revokes",async()=>{const db=await migrated();const f=await db.query<{proname:string;config:string;execute:boolean}>(`SELECT proname,COALESCE(array_to_string(proconfig,','),'') config,has_function_privilege('public',oid,'EXECUTE') execute FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname IN('strategy_lab_validate_snapshot_item_asof','strategy_lab_validate_snapshot_item_completeness','odds_snapshots_reject_mutation') ORDER BY proname`);expect(f.rows).toHaveLength(3);for(const row of f.rows){expect(row.config).toContain('search_path=pg_catalog, public');expect(row.execute).toBe(false);}const i=await db.query<{indexname:string}>(`SELECT indexname FROM pg_indexes WHERE indexname IN('odds_snapshots_strategy_lab_evidence_idx','strategy_lab_snapshot_items_one_current_unique') ORDER BY indexname`);expect(i.rows).toHaveLength(2);const t=await db.query<{tgname:string;deferred:boolean}>(`SELECT tgname,tginitdeferred deferred FROM pg_trigger WHERE tgname IN('strategy_lab_snapshot_sets_require_items','strategy_lab_snapshot_items_require_valid_set','odds_snapshots_append_only') ORDER BY tgname`);expect(t.rows).toHaveLength(3);expect(t.rows.filter(x=>x.tgname.includes('require')).every(x=>x.deferred)).toBe(true);const r=await db.query<{relrowsecurity:boolean;relforcerowsecurity:boolean;public_select:boolean}>(`SELECT relrowsecurity,relforcerowsecurity,has_table_privilege('public',oid,'SELECT') public_select FROM pg_class WHERE oid='strategy_lab_snapshot_items'::regclass`);expect(r.rows[0]).toEqual({relrowsecurity:true,relforcerowsecurity:true,public_select:false});});
 it("keeps 0022, setup, Drizzle, roles and readiness representations in parity",async()=>{const [migration,setup,schema,roles,readiness]=await Promise.all([read("migrations/0022_strategy_lab_snapshot_provider.sql"),read("setup-database.sql"),read("src/storage/database/shared/schema.ts"),read("infra/local-data/sql/strategy-lab-roles.sql"),read("src/features/strategy-lab/production-readiness.ts")]);for(const token of ["hash_version","canonical_content_hash","odds_snapshots_hash_contract_check","odds_snapshots_strategy_lab_evidence_idx","strategy_lab_snapshot_items_one_current_unique","strategy_lab_validate_snapshot_item_asof","strategy_lab_validate_snapshot_item_completeness","odds_snapshots_reject_mutation","0022_strategy_lab_snapshot_provider"]){expect(setup,token).toContain(token);expect(migration,token).toContain(token);}expect(schema).toContain('hashVersion: text("hash_version")');expect(schema).toContain('canonicalContentHash: text("canonical_content_hash")');expect(schema).toContain('strategy_lab_snapshot_items_one_current_unique');expect(roles).toContain("GRANT SELECT ON TABLE %I TO strategy_lab_reader,strategy_lab_writer");expect(roles).toContain("'odds_snapshots','match_results','strategy_versions'");expect(roles).not.toMatch(/GRANT (INSERT|UPDATE|DELETE).*odds_snapshots/i);expect(readiness).toContain('0023_strategy_lab_trusted_settlement');expect(setup).toContain('DEFERRABLE INITIALLY DEFERRED');expect(setup).toContain('BEFORE UPDATE OR DELETE ON odds_snapshots');});
});
