import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
const root=new URL("..",import.meta.url);const read=(p:string)=>readFile(new URL(p,root),"utf8");const uuid=(n:number)=>`10000000-0000-4000-8000-${String(n).padStart(12,"0")}`;const hash=(v:string)=>createHash("sha256").update(v).digest("hex");let db:PGlite;
beforeAll(async()=>{db=new PGlite();await db.exec(`CREATE TABLE schema_migrations(version VARCHAR(100) PRIMARY KEY,description TEXT NOT NULL);CREATE TABLE user_focused_leagues(id SERIAL PRIMARY KEY,league_name TEXT NOT NULL UNIQUE);CREATE TABLE odds_snapshots(id SERIAL PRIMARY KEY,match_id VARCHAR(20) NOT NULL,match_date VARCHAR(8) NOT NULL,company_id VARCHAR(20) NOT NULL,market_type TEXT NOT NULL,snapshot_type TEXT NOT NULL,source TEXT NOT NULL,odds JSONB NOT NULL,source_observed_at TIMESTAMPTZ,collected_at TIMESTAMPTZ NOT NULL,content_hash TEXT NOT NULL,idempotency_key TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE strategy_versions(version TEXT PRIMARY KEY);CREATE TABLE prediction_results(id SERIAL PRIMARY KEY);CREATE TABLE match_results(id SERIAL PRIMARY KEY,match_id VARCHAR(20) NOT NULL,match_date VARCHAR(8) NOT NULL);`);await db.exec(await read("migrations/0020_strategy_lab_fact_model.sql"));await db.exec(await read("migrations/0021_strategy_lab_policy_and_artifacts.sql"));},30_000);afterAll(async()=>db.close());

const fact=(id:number,revision:number,raw:string,normalized:string,observed:string,cutoff:string,supersedes?:number)=>`INSERT INTO strategy_lab_match_facts(id,match_id,match_date,league_name_raw,league_name_normalized,kickoff_at,source,source_observed_at,dataset_cutoff_at,canonical_payload,content_hash,revision,supersedes_id,schema_version,trace_id) VALUES('${uuid(id)}','m1','20260717','${raw}','${normalized}','2026-07-17T15:00Z','schedule','${observed}','${cutoff}',jsonb_build_object('schemaVersion',1,'matchId','m1','matchDate','20260717','league','${normalized}','kickoffAt','2026-07-17T15:00Z'::timestamptz,'source','schedule','sourceObservedAt','${observed}'::timestamptz,'datasetCutoffAt','${cutoff}'::timestamptz,'revision',${revision}),'${hash(String(id))}',${revision},${supersedes?`'${uuid(supersedes)}'`:'NULL'},1,'trace')`;
const artifact=(strategy:string,version:string,h:string)=>{const definition=strategy==='C'?{strategyId:strategy,version,executable:true,fallback:"A",completeWithoutExecutor:"unavailable"}:strategy==='D'?{strategyId:strategy,version,executable:false,availability:"compatibility-only"}:{strategyId:strategy,version,executable:true,deterministic:true};const json=JSON.stringify(definition).replaceAll("'","''");return `INSERT INTO strategy_lab_strategy_artifacts(strategy_id,version,artifact_hash,engine_version,definition,canonical_payload,code_compatibility,schema_version,behavior_corpus_hash,executable,created_by,trace_id) VALUES('${strategy}','${version}','${h}','engine','${json}',jsonb_build_object('schemaVersion',1,'engineVersion','engine','codeCompatibility','compat','behaviorCorpusHash','${hash("corpus")}','definition','${json}'::jsonb),'compat',1,'${hash("corpus")}',${strategy==='D'?'false':'true'},'tester','trace')`};

describe("strategy lab 0021 temporal integrity",()=>{
 it("shares explicit Unicode canonicalization and enforces match revision monotonicity",async()=>{
  const rows=await db.query<{v:string}>(`SELECT strategy_lab_canonicalize_text(E' \tCafe\u0301\u00a0\u202F\u3000联赛\r\n ') v`);expect(rows.rows[0].v).toBe("Café 联赛");
  await expect(db.exec(fact(1,1," Café　联赛 ","Café 联赛","2026-07-17T10:00Z","2026-07-17T12:00Z"))).rejects.toBeDefined();
  await db.exec(fact(1,1," Café　联赛 ","Café 联赛","2026-07-17T10:00Z","2026-07-17T12:00Z"));
  await expect(db.exec(fact(2,2,"Café 联赛","Café 联赛","2026-07-17T09:00Z","2026-07-17T12:00Z",1))).rejects.toBeDefined();
  await db.exec(fact(2,2,"Café 联赛","Café 联赛","2026-07-17T11:00Z","2026-07-17T13:00Z",1));
  await expect(db.exec(fact(3,2,"Café 联赛","Café 联赛","2026-07-17T11:00Z","2026-07-17T13:00Z",1))).rejects.toBeDefined();
   await expect(db.exec(`UPDATE strategy_lab_match_facts SET trace_id='x' WHERE id='${uuid(1)}'`)).rejects.toBeDefined();
  });
 it("rejects forged normalized values, canonical payloads and reversed observation time",async()=>{
  await expect(db.exec(fact(4,1,"英超","西甲","2026-07-17T10:00Z","2026-07-17T12:00Z"))).rejects.toBeDefined();
  await expect(db.exec(fact(5,1,"英超","英超","2026-07-17T13:00Z","2026-07-17T12:00Z"))).rejects.toBeDefined();
  await expect(db.exec(fact(6,1,"英超","英超","2026-07-17T10:00Z","2026-07-17T12:00Z").replace("'revision',1","'revision',99"))).rejects.toBeDefined();
 });
 it("separates immutable policy content from repeatable captures",async()=>{
  const h=hash("policy");const payload=`jsonb_build_object('schemaVersion',1,'mode','user_focused_leagues','leagues','["Café 联赛","英超"]'::jsonb)`;
  await db.exec(`INSERT INTO strategy_lab_league_policy_artifacts(content_hash,version_hash,mode,leagues,canonical_payload,source_row_count,schema_version) VALUES('${h}','${h}','user_focused_leagues','["Café 联赛","英超"]',${payload},2,1)`);
  await db.exec(`INSERT INTO strategy_lab_league_policy_captures(id,artifact_hash,dataset_cutoff_at,captured_at,source_history_cutoff,evidence_hash,created_by,trace_id) VALUES('${uuid(10)}','${h}','2026-07-17T10:00Z','2026-07-17T12:00Z','2026-07-17T10:00Z','${hash("e1")}','actor','t'),('${uuid(11)}','${h}','2026-07-17T11:00Z','2026-07-17T12:00Z','2026-07-17T11:00Z','${hash("e2")}','actor','t')`);
  const captures=await db.query<{artifact_hash:string}>("SELECT artifact_hash FROM strategy_lab_league_policy_captures ORDER BY id");expect(captures.rows).toHaveLength(2);expect(new Set(captures.rows.map(x=>x.artifact_hash)).size).toBe(1);
  await expect(db.exec(`DELETE FROM strategy_lab_league_policy_artifacts WHERE content_hash='${h}'`)).rejects.toBeDefined();
  const unsorted=hash("unsorted");await expect(db.exec(`INSERT INTO strategy_lab_league_policy_artifacts(content_hash,version_hash,mode,leagues,canonical_payload,source_row_count,schema_version) VALUES('${unsorted}','${unsorted}','user_focused_leagues','["英超","Café 联赛"]',jsonb_build_object('schemaVersion',1,'mode','user_focused_leagues','leagues','["英超","Café 联赛"]'::jsonb),2,1)`)).rejects.toBeDefined();
 });
 it("accepts a complete baseline transaction and rejects incomplete or empty baselines",async()=>{
  const baseline=uuid(30),payload=`jsonb_build_object('schemaVersion',1,'baselineId','${baseline}'::uuid,'source','admin','sourceObservedAt','2026-07-17T10:00Z'::timestamptz,'leagues','["英超"]'::jsonb)`;
  await db.exec(`BEGIN;INSERT INTO strategy_lab_focused_league_baselines(id,source,source_observed_at,dataset_cutoff_at,canonical_payload,content_hash,member_count,is_complete,completed_at,actor,trace_id) VALUES('${baseline}','admin','2026-07-17T10:00Z','2026-07-17T10:00Z',${payload},'${hash("baseline")}',1,true,'2026-07-17T10:00Z','actor','t');INSERT INTO strategy_lab_focused_league_events(id,baseline_id,source,league_name_raw,league_name_normalized,action,source_observed_at,dataset_cutoff_at,canonical_payload,content_hash,revision,actor,trace_id) VALUES('${uuid(31)}','${baseline}','admin','英超','英超','add','2026-07-17T10:00Z','2026-07-17T10:00Z',jsonb_build_object('schemaVersion',1,'baselineId','${baseline}'::uuid,'source','admin','league','英超','action','add','sourceObservedAt','2026-07-17T10:00Z'::timestamptz,'datasetCutoffAt','2026-07-17T10:00Z'::timestamptz,'revision',1),'${hash("event")}',1,'actor','t');COMMIT;`);
  await expect(db.exec(`INSERT INTO strategy_lab_focused_league_baselines(id,source,source_observed_at,dataset_cutoff_at,canonical_payload,content_hash,member_count,is_complete,completed_at,actor,trace_id) VALUES('${uuid(32)}','admin','2026-07-17T10:00Z','2026-07-17T10:00Z',jsonb_build_object('schemaVersion',1,'baselineId','${uuid(32)}'::uuid,'source','admin','sourceObservedAt','2026-07-17T10:00Z'::timestamptz,'leagues','[]'::jsonb),'${hash("empty")}',0,true,'2026-07-17T10:00Z','actor','t')`)).rejects.toBeDefined();
 });
 it("keeps artifact identity immutable and publication revisions continuous",async()=>{
  const a1=hash("a1"),a2=hash("a2");await db.exec(artifact("A","A-v1",a1));await db.exec(artifact("A","A-v2",a2));
  await db.exec(`INSERT INTO strategy_lab_strategy_publications(id,root_id,artifact_hash,status,effective_from,revision,published_at,actor,trace_id) VALUES('${uuid(20)}','${uuid(20)}','${a1}','published','2026-07-17T10:00Z',1,'2026-07-17T10:00Z','actor','t')`);
  await expect(db.exec(`INSERT INTO strategy_lab_strategy_publications(id,root_id,artifact_hash,status,effective_from,revision,published_at,actor,trace_id) VALUES('${uuid(21)}','${uuid(21)}','${a2}','published','2026-07-17T11:00Z',1,'2026-07-17T11:00Z','actor','t')`)).rejects.toBeDefined();
  await db.exec(`INSERT INTO strategy_lab_strategy_publications(id,root_id,artifact_hash,status,effective_from,effective_to,revision,supersedes_id,published_at,retired_at,actor,trace_id) VALUES('${uuid(22)}','${uuid(20)}','${a1}','retired','2026-07-17T10:00Z','2026-07-17T11:00Z',2,'${uuid(20)}','2026-07-17T11:00Z','2026-07-17T11:00Z','actor','t')`);
  await db.exec(`INSERT INTO strategy_lab_strategy_publications(id,root_id,artifact_hash,status,effective_from,revision,published_at,actor,trace_id) VALUES('${uuid(21)}','${uuid(21)}','${a2}','published','2026-07-17T11:00Z',1,'2026-07-17T11:00Z','actor','t')`);
  await expect(db.exec(`UPDATE strategy_lab_strategy_artifacts SET version='bad' WHERE artifact_hash='${a1}'`)).rejects.toBeDefined();
 });
 it("registers 0020 then 0021 and forces RLS without PUBLIC privileges or anonymous policies",async()=>{const migrations=await db.query<{version:string}>("SELECT version FROM schema_migrations ORDER BY version");expect(migrations.rows.map(row=>row.version)).toEqual(["0020_strategy_lab_fact_model","0021_strategy_lab_policy_and_artifacts"]);const rows=await db.query<{relrowsecurity:boolean;relforcerowsecurity:boolean}>("SELECT relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname IN('strategy_lab_match_facts','strategy_lab_focused_league_baselines','strategy_lab_focused_league_events','strategy_lab_league_policy_artifacts','strategy_lab_league_policy_captures','strategy_lab_strategy_artifacts','strategy_lab_strategy_publications','strategy_lab_build_artifacts') AND relkind='r'");expect(rows.rows).toHaveLength(8);expect(rows.rows.every(x=>x.relrowsecurity&&x.relforcerowsecurity)).toBe(true);expect((await db.query("SELECT * FROM pg_policies WHERE tablename IN('strategy_lab_match_facts','strategy_lab_focused_league_baselines','strategy_lab_focused_league_events','strategy_lab_league_policy_artifacts','strategy_lab_league_policy_captures','strategy_lab_strategy_artifacts','strategy_lab_strategy_publications','strategy_lab_build_artifacts')")).rows).toHaveLength(0);const grants=await db.query("SELECT 1 FROM information_schema.role_table_grants WHERE grantee='PUBLIC' AND table_name IN('strategy_lab_match_facts','strategy_lab_focused_league_baselines','strategy_lab_focused_league_events','strategy_lab_league_policy_artifacts','strategy_lab_league_policy_captures','strategy_lab_strategy_artifacts','strategy_lab_strategy_publications','strategy_lab_build_artifacts')");expect(grants.rows).toHaveLength(0);});
});
