import { NextRequest, NextResponse } from "next/server";
import { requireAdminCapability } from "@/lib/auth/admin-capabilities";
import { getBacktestLimits } from "@/lib/backtest/limits";
import { getSupabaseClient } from "@/storage/database/supabase-client";
import { runRouteCommand, CommandRateLimitError } from "@/features/management/route-command";
import { CommandConflictError } from "@/features/management/commands";
import { backtestAnalysisServices } from "@/adapters/backtest-analysis";
import { POST as runBacktest, DELETE as cancelBacktest } from "@/features/backtest/runtime";
export async function GET(request:NextRequest){const auth=await requireAdminCapability(request,"admin:view");if(!auth.ok)return NextResponse.json({success:false,error:auth.error},{status:auth.status});const {data,error}=await getSupabaseClient().from("backtest_jobs").select("id,status,current_step,start_date,end_date,current_date,total_dates,processed_dates,total_matches,analyzed_matches,verified_matches,correct_matches,accuracy,log,result,last_error,started_at,ended_at,updated_at").order("updated_at",{ascending:false}).limit(100);if(error)return NextResponse.json({success:false,error:"回测任务暂时不可用"},{status:503});return NextResponse.json({success:true,limits:getBacktestLimits(),items:data||[]},{headers:{"Cache-Control":"private, no-store"}});}
export async function POST(request:NextRequest){const auth=await requireAdminCapability(request,"admin:execute");if(!auth.ok)return NextResponse.json({success:false,error:auth.error},{status:auth.status});return runRouteCommand(request,auth.principal,"backtest.lifecycle",async(payload,targetId)=>{let response:Response;if(targetId==="backtest.cancel"){const jobId=typeof payload.jobId==="string"?payload.jobId:"";if(!jobId)throw new Error("jobId required");response=await cancelBacktest(new NextRequest(`${request.nextUrl.origin}/api/backtest?id=${encodeURIComponent(jobId)}`,{method:"DELETE"}));}else if(targetId==="backtest.resume"){const jobId=typeof payload.jobId==="string"?payload.jobId:"";if(!jobId)throw new Error("jobId required");response=await runBacktest(new NextRequest(`${request.nextUrl.origin}/api/backtest`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({resumeJobId:jobId})}),backtestAnalysisServices);}else{response=await runBacktest(new NextRequest(`${request.nextUrl.origin}/api/backtest`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),backtestAnalysisServices);}const result=await response.json() as Record<string,unknown>;if(!response.ok){const message=typeof result.error==="string"?result.error:"回测命令失败";if(response.status===429)throw new CommandRateLimitError(message);if(response.status===409)throw new CommandConflictError(message);throw new Error(message);}return result;});}
