"use client";
import { useCallback,useEffect,useState } from "react";
import { useSearchParams } from "next/navigation";
import { AlertCircle,Check,Clipboard,RefreshCw,Search,ShieldCheck } from "lucide-react";
import { Alert,AlertDescription,AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import { Tabs,TabsList,TabsTrigger } from "@/components/ui/tabs";

type Tab="matrix"|"decision"|"report"|"shadow";
type PageInfo={limit:number;hasMore:boolean;nextCursor:string|null};
type Envelope<T>={data:T;requestId:string;pageInfo:PageInfo|null};
type Run={id:string;status:string;startDate:string;endDate:string;datasetMode:string;createdAt:string;coverage:{predictions:number;matches:number;settled:number};auditStatus:string};
type Metric={counted:number;unavailable:number;outcomes:{win:number;halfWin:number;push:number;halfLoss:number;loss:number};profitMicros:string;stakeMicros:string;roi:string|null};
type Cell={strategy:"A"|"B"|"C"|"D";checkpoint:string;sample:number;fallback:number;executable:boolean;compatibilityOnly:boolean;decisions:{recommend:number;observe:number;reanalyze:number;insufficient:number};snapshotQuality:Record<string,number>;actual:Metric;theoretical:Metric};
type Overview={coverage:{predictions:number;matches:number;recommend:number;observe:number;reanalyze:number;insufficient:number;cFallback:number;dBaseline:number};policy:{capture:{mode:string;artifactHash:string|null;captureId:string|null;capturedAt:string|null};currentChanged:"unknown"|boolean};health:{reader:string}};
type ReportSummary={validSample:number;coverage:{matches:number;recommend:number;observe:number;reanalyze:number;insufficient:number};cFallback:number;dBaseline:number;actual:Metric;theoretical:Metric;metricDefinitions:Record<string,string>;timeSeries:null};
type Prediction={id:string;matchId:string;matchDate:string;checkpoint:string;requestedStrategy:string;executedStrategy:string;fallback:boolean;fallbackReason:string|null;compatibilityOnly:boolean;decisionStatus:string;selection:string|null;inputHash:string;outputHash:string;snapshotHash:string;createdAt:string};
type Revision={id:string;revision:number;quoteBasis:string;outcome:string;profitMicros:string|null;isCounted:boolean;evidenceHash:string|null;calculatorVersion:string|null;quoteHandicapRaw:string|null;quoteSelectedWaterMillionths:number|null;scoreRevision:number|null;scoreRevisionHash:string|null;current:boolean;superseded:boolean;excludedFromStatistics:boolean;settledAt:string};
type Chain={integrity:{revision:string;quoteDrift:string};revisions:Revision[]};
const tabValues:Tab[]=["matrix","decision","report","shadow"];
const labels={matrix:"策略矩阵",decision:"决策证据",report:"观察报告",shadow:"影子运行"};
class QueryError extends Error{constructor(readonly status:number,readonly requestId:string,message:string){super(message)}}
async function read<T>(url:string,signal?:AbortSignal):Promise<Envelope<T>>{const response=await fetch(url,{method:"GET",credentials:"same-origin",headers:{Accept:"application/json"},signal});const body=await response.json().catch(()=>({}));if(!response.ok)throw new QueryError(response.status,String(body.requestId||response.headers.get("x-request-id")||"未知"),String(body.message||"读取失败"));return body as Envelope<T>}

export function StrategyLabView(){
 const search=useSearchParams(),searchKey=search.toString();
 const tab=tabValues.includes(search.get("tab") as Tab)?search.get("tab") as Tab:"matrix";
 const [runs,setRuns]=useState<Run[]>([]),[runsPage,setRunsPage]=useState<PageInfo|null>(null),[runId,setRunId]=useState(search.get("runId")||"");
 const [overview,setOverview]=useState<Overview|null>(null),[cells,setCells]=useState<Cell[]>([]),[report,setReport]=useState<ReportSummary|null>(null),[predictions,setPredictions]=useState<Prediction[]>([]),[predictionPage,setPredictionPage]=useState<PageInfo|null>(null),[auditPending,setAuditPending]=useState(false);
 const [q,setQ]=useState(""),[expert,setExpert]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<QueryError|null>(null),[version,setVersion]=useState(0);
 const [chainOpen,setChainOpen]=useState(false),[chain,setChain]=useState<Chain|null>(null),[chainError,setChainError]=useState<QueryError|null>(null),[chainLoading,setChainLoading]=useState(false);
 const navigate=useCallback((next:Tab,id=runId)=>{const p=new URLSearchParams(searchKey);p.set("tab",next);if(id)p.set("runId",id);window.history.replaceState(null,"",`?${p}`)},[runId,searchKey]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError(null);read<Run[]>("/api/admin/strategy-lab/runs?runType=shadow&limit=50",controller.signal).then(async response=>{setRuns(response.data);setRunsPage(response.pageInfo);const id=runId||response.data[0]?.id||"";if(!id)return;const query=q?`&q=${encodeURIComponent(q)}`:"";const [o,m,r,p,a]=await Promise.all([read<Overview>(`/api/admin/strategy-lab/runs/${id}/overview`,controller.signal),read<Cell[]>(`/api/admin/strategy-lab/runs/${id}/matrix`,controller.signal),read<ReportSummary>(`/api/admin/strategy-lab/runs/${id}/report`,controller.signal),read<Prediction[]>(`/api/admin/strategy-lab/predictions?runId=${id}&limit=50${query}`,controller.signal),read<Record<string,unknown>[]>(`/api/admin/strategy-lab/runs/${id}/audit?limit=50`,controller.signal)]);setOverview(o.data);setCells(m.data);setReport(r.data);setPredictions(p.data);setPredictionPage(p.pageInfo);setAuditPending(response.data.find(item=>item.id===id)?.auditStatus==="audit_pending"||a.data.some(item=>item.status==="audit_pending"));if(!runId){setRunId(id);navigate(tab,id)}}).catch(cause=>{if(!(cause instanceof DOMException&&cause.name==="AbortError"))setError(cause instanceof QueryError?cause:new QueryError(503,"未知","只读查询服务暂不可用"))}).finally(()=>setLoading(false));return()=>controller.abort()},[navigate,q,runId,tab,version]);
 const loadChain=async(predictionId:string)=>{setChainOpen(true);setChain(null);setChainError(null);setChainLoading(true);try{setChain((await read<Chain>(`/api/admin/strategy-lab/predictions/${predictionId}/settlement-chain`)).data)}catch(cause){setChainError(cause instanceof QueryError?cause:new QueryError(503,"未知","修订链读取失败"))}finally{setChainLoading(false)}};
 const loadMorePredictions=async()=>{if(!predictionPage?.nextCursor)return;const query=q?`&q=${encodeURIComponent(q)}`:"";const response=await read<Prediction[]>(`/api/admin/strategy-lab/predictions?runId=${runId}&limit=50${query}&cursor=${encodeURIComponent(predictionPage.nextCursor)}`);setPredictions(current=>[...current,...response.data]);setPredictionPage(response.pageInfo)};
 const loadMoreRuns=async()=>{if(!runsPage?.nextCursor)return;const response=await read<Run[]>(`/api/admin/strategy-lab/runs?runType=shadow&limit=50&cursor=${encodeURIComponent(runsPage.nextCursor)}`);setRuns(current=>[...current,...response.data]);setRunsPage(response.pageInfo)};
 const selected=runs.find(item=>item.id===runId);
 return <main className="mx-auto w-full min-w-0 max-w-[1600px] space-y-5 overflow-x-clip p-4 motion-reduce:scroll-auto md:p-6"><header className="flex min-w-0 flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold">Strategy Lab 管理观察台</h1><Badge variant="outline" className="border-cyan-500/40">只读</Badge></div><p className="mt-1 text-sm text-muted-foreground">服务端统计 · actual/theoretical 严格隔离</p></div><div className="flex min-w-0 gap-2"><Select value={runId} onValueChange={id=>{setRunId(id);navigate(tab,id)}}><SelectTrigger aria-label="选择运行" className="min-h-11 w-full min-w-0 sm:w-80"><SelectValue placeholder="选择影子运行"/></SelectTrigger><SelectContent>{runs.map(item=><SelectItem key={item.id} value={item.id}>{item.id.slice(0,8)} · {item.status}</SelectItem>)}</SelectContent></Select><Button aria-label="重新读取" variant="outline" size="icon" className="size-11 shrink-0 focus-visible:ring-2" onClick={()=>setVersion(value=>value+1)}><RefreshCw/></Button></div></header>
 <Alert className="border-cyan-500/30 bg-cyan-500/5"><ShieldCheck/><AlertTitle>影子隔离，不影响正式预测/通知/学习</AlertTitle><AlertDescription>观察台只读取冻结证据与服务端统计，不改变任何业务事实。</AlertDescription></Alert>
 <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><Badge variant={overview?.health.reader==="ready"?"outline":"destructive"}>Reader {overview?.health.reader||"checking"}</Badge>{auditPending?<Badge variant="outline" className="border-amber-500 text-amber-700 dark:text-amber-300">Audit pending</Badge>:<Badge variant="outline">Audit ready</Badge>}{selected?<span>{selected.startDate}–{selected.endDate} · {selected.datasetMode}</span>:null}{overview?<span>Policy {overview.policy.capture.artifactHash?.slice(0,10)||"unknown"} · current changed {String(overview.policy.currentChanged)}</span>:null}</div>
 <Tabs value={tab} onValueChange={value=>navigate(value as Tab)}><TabsList className="grid h-auto min-h-11 grid-cols-2 md:w-fit md:grid-cols-4">{tabValues.map(value=><TabsTrigger className="min-h-11 focus-visible:ring-2" key={value} value={value}>{labels[value]}</TabsTrigger>)}</TabsList></Tabs>
 {loading?<Loading/>:error?<ErrorView error={error} retry={()=>setVersion(value=>value+1)}/>:!runId?<Empty text="暂无影子运行"/>:tab==="matrix"?<Matrix cells={cells}/>:tab==="decision"?<Decision items={predictions} q={q} setQ={setQ} expert={expert} setExpert={setExpert} showMore={Boolean(predictionPage?.hasMore)} more={()=>void loadMorePredictions()} chain={id=>void loadChain(id)}/>:tab==="report"?<Report summary={report}/>:<Shadow runs={runs} auditPending={auditPending} showMore={Boolean(runsPage?.hasMore)} more={()=>void loadMoreRuns()} select={id=>{setRunId(id);navigate("matrix",id)}}/>}
 <ChainDialog open={chainOpen} setOpen={setChainOpen} loading={chainLoading} value={chain} error={chainError}/></main>;
}

function Matrix({cells}:{cells:Cell[]}){return <section aria-label="12格策略矩阵" className="min-w-0 space-y-4">{["A","B","C","D"].map(strategy=><Card key={strategy} className="min-w-0 overflow-hidden"><CardHeader><div className="flex flex-wrap justify-between gap-2"><CardTitle>策略 {strategy}</CardTitle>{strategy==="D"?<Badge variant="outline">Compatibility-only · 不可执行</Badge>:strategy==="C"?<Badge variant="outline">requested C 归组</Badge>:null}</div></CardHeader><CardContent className="min-w-0 p-0"><div className="hidden min-w-0 overflow-x-auto lg:block"><Table><TableHeader><TableRow><TableHead>Checkpoint</TableHead><TableHead>样本</TableHead><TableHead>覆盖</TableHead><TableHead>Actual</TableHead><TableHead>Theoretical</TableHead></TableRow></TableHeader><TableBody>{cells.filter(cell=>cell.strategy===strategy).map(cell=><TableRow key={cell.checkpoint}><TableCell>{cell.checkpoint}</TableCell><TableCell>{cell.sample||"—"}{cell.fallback?` · C→A ${cell.fallback}`:""}</TableCell><TableCell>{cell.decisions.recommend}/{cell.decisions.observe}/{cell.decisions.reanalyze}/{cell.decisions.insufficient}</TableCell><TableCell><Metric value={cell.actual} kind="actual"/></TableCell><TableCell><Metric value={cell.theoretical} kind="theoretical"/></TableCell></TableRow>)}</TableBody></Table></div><div data-testid="matrix-mobile-cards" className="grid gap-3 p-4 lg:hidden">{cells.filter(cell=>cell.strategy===strategy).map(cell=><article key={cell.checkpoint} className="min-w-0 rounded-xl border p-4"><div className="flex justify-between gap-2"><b>{cell.checkpoint}</b><span>{cell.sample?`${cell.sample} 样本`:"暂无样本"}</span></div><p className="mt-2 text-xs text-muted-foreground">覆盖 推{cell.decisions.recommend}/观{cell.decisions.observe}/重{cell.decisions.reanalyze}/缺{cell.decisions.insufficient}{cell.fallback?` · C→A ${cell.fallback}`:""}</p><div className="mt-3 grid gap-2"><Metric value={cell.actual} kind="actual"/><Metric value={cell.theoretical} kind="theoretical"/></div></article>)}</div></CardContent></Card>)}</section>}
function Metric({value,kind}:{value:Metric;kind:"actual"|"theoretical"}){return <div className={kind==="actual"?"rounded-lg bg-blue-500/10 p-3":"rounded-lg border border-cyan-500/40 p-3"}><b>{kind==="actual"?"Actual 实际":"Theoretical 理论"}</b>{kind==="theoretical"?<p className="text-[11px] text-cyan-700 dark:text-cyan-300">不代表实际可成交报价</p>:null}<p className="text-xs text-muted-foreground">计入 {value.counted} · unavailable {value.unavailable} · ROI {value.roi??"—"}</p><div aria-label="五级结算" className="mt-2 flex gap-1">{Object.entries(value.outcomes).map(([key,count])=><i key={key} title={`${key} ${count}`} className="h-2 min-w-2 rounded-full bg-blue-500/60" style={{flexGrow:Math.max(1,count)}}/>)}</div></div>}
function Decision({items,q,setQ,expert,setExpert,showMore,more,chain}:{items:Prediction[];q:string;setQ:(value:string)=>void;expert:boolean;setExpert:(value:boolean)=>void;showMore:boolean;more:()=>void;chain:(id:string)=>void}){return <section className="space-y-3"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 size-4"/><Input className="min-h-11 pl-9" value={q} onChange={event=>setQ(event.target.value)} placeholder="搜索 prediction / 赛事"/></div><Button className="min-h-11" variant="outline" onClick={()=>setExpert(!expert)}>{expert?"简明":"专业"}</Button></div>{items.length?items.map(item=><Card key={item.id}><CardHeader><CardTitle className="text-base">赛事 {item.matchId}</CardTitle><CardDescription>{item.matchDate} · {item.checkpoint} · requested {item.requestedStrategy} → {item.executedStrategy}</CardDescription></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Badge>{item.decisionStatus}</Badge>{item.fallback?<Badge variant="outline">C→A fallback</Badge>:null}{item.compatibilityOnly?<Badge variant="outline">D baseline</Badge>:null}</div><div className="grid grid-cols-3 gap-2 text-center text-xs"><span className="rounded-lg border p-2">T1215</span><span className="rounded-lg border p-2">T30</span><span className="rounded-lg border p-2">T03</span></div><p className="text-sm">选择 {item.selection||"—"}{item.fallbackReason?` · ${item.fallbackReason}`:""}</p>{expert?<div className="grid gap-2 sm:grid-cols-3"><Hash label="Input" value={item.inputHash}/><Hash label="Output" value={item.outputHash}/><Hash label="Evidence" value={item.snapshotHash}/></div>:null}<Button className="min-h-11" variant="outline" onClick={()=>chain(item.id)}>查看结算修订</Button></CardContent></Card>):<Empty text="没有匹配决策"/>}{showMore?<Button className="min-h-11 w-full" variant="outline" onClick={more}>加载更多决策</Button>:null}</section>}
function Report({summary}:{summary:ReportSummary|null}){if(!summary)return <Empty text="暂无服务端报告"/>;return <section className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><Card className="bg-blue-500/10"><CardHeader><CardTitle>Actual 实际</CardTitle><CardDescription>服务端 latest revision + is_counted</CardDescription></CardHeader><CardContent><Metric value={summary.actual} kind="actual"/></CardContent></Card><Card className="border-cyan-500/40"><CardHeader><CardTitle>Theoretical 理论</CardTitle><CardDescription>不代表实际可成交报价</CardDescription></CardHeader><CardContent><Metric value={summary.theoretical} kind="theoretical"/></CardContent></Card></div><Card><CardContent className="grid gap-3 p-5 text-sm sm:grid-cols-3"><span>有效样本 {summary.validSample}</span><span>赛事覆盖 {summary.coverage.matches}</span><span>推荐 {summary.coverage.recommend}</span><span>观察 {summary.coverage.observe}</span><span>重分析 {summary.coverage.reanalyze}</span><span>数据不足 {summary.coverage.insufficient}</span><span>C→A {summary.cFallback}</span><span>D baseline {summary.dBaseline}</span></CardContent></Card><Alert><AlertCircle/><AlertTitle>当前版本暂未提供时间序列</AlertTitle><AlertDescription>不伪造趋势图；所有数字均为 report API 返回的服务端统计。</AlertDescription></Alert></section>}
function Shadow({runs,auditPending,showMore,more,select}:{runs:Run[];auditPending:boolean;showMore:boolean;more:()=>void;select:(id:string)=>void}){return <section className="space-y-3">{runs.map(item=><Card key={item.id}><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-sm">{item.id}</p><p className="text-sm text-muted-foreground">{item.status} · {item.coverage.matches} 场 · {item.auditStatus}</p></div><Button className="min-h-11" variant="outline" onClick={()=>select(item.id)}>查看详情</Button></CardContent></Card>)}{showMore?<Button className="min-h-11 w-full" variant="outline" onClick={more}>加载更多运行</Button>:null}<p className={auditPending?"text-xs text-amber-700 dark:text-amber-300":"text-xs text-muted-foreground"}>{auditPending?"安全审计尚在等待，不视为完全成功。":"安全审计摘要已读取。"}</p></section>}
function ChainDialog({open,setOpen,loading,value,error}:{open:boolean;setOpen:(value:boolean)=>void;loading:boolean;value:Chain|null;error:QueryError|null}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-3xl"><DialogHeader><DialogTitle>结算修订链</DialogTitle><DialogDescription>冻结报价和比分修订的只读证据时间轴</DialogDescription></DialogHeader>{loading?<Loading/>:error?<ErrorView error={error}/>:!value||!value.revisions.length?<Empty text="暂无结算修订"/>:<div className="space-y-3"><div className="flex gap-2"><Badge variant="outline">Revision {value.integrity.revision}</Badge><Badge variant="outline">Quote drift {value.integrity.quoteDrift}</Badge></div>{value.revisions.map(revision=><article key={revision.id} className={revision.current?"rounded-xl border border-blue-500/40 bg-blue-500/5 p-4":"rounded-xl border p-4 opacity-75"}><div className="flex flex-wrap items-center justify-between gap-2"><b>Revision {revision.revision}</b><div className="flex gap-2">{revision.current?<Badge>current</Badge>:null}{revision.superseded?<Badge variant="outline">superseded</Badge>:null}{revision.excludedFromStatistics?<Badge variant="outline">excluded</Badge>:null}</div></div><p className="mt-2 text-sm">{revision.quoteBasis} · {revision.outcome} · profitMicros {revision.profitMicros??"—"} · score revision {revision.scoreRevision??"—"}</p><p className="text-xs text-muted-foreground">冻结报价 {revision.quoteHandicapRaw??"—"} / {revision.quoteSelectedWaterMillionths??"—"} · {revision.calculatorVersion??"legacy"}</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><Hash label="Evidence" value={revision.evidenceHash||""}/><Hash label="Score" value={revision.scoreRevisionHash||""}/></div></article>)}</div>}</DialogContent></Dialog>}
function Hash({label,value}:{label:string;value:string}){const[done,setDone]=useState(false);return <div className="flex min-h-11 items-center justify-between rounded-lg border px-3 text-xs"><span>{label} · {value?`${value.slice(0,10)}…`:"—"}</span><Button disabled={!value} aria-label={`复制${label}完整值`} size="icon" variant="ghost" className="size-11" onClick={()=>void navigator.clipboard.writeText(value).then(()=>setDone(true))}>{done?<Check/>:<Clipboard/>}</Button></div>}
function Loading(){return <div className="grid gap-4 md:grid-cols-3">{Array.from({length:6},(_,index)=><Skeleton className="h-40" key={index}/>)}</div>}
function Empty({text}:{text:string}){return <Card><CardContent className="p-10 text-center text-muted-foreground">{text}</CardContent></Card>}
function ErrorView({error,retry}:{error:QueryError;retry?:()=>void}){const title=error.status===503?"只读查询服务暂不可用":error.status===403?"没有查看权限":error.status===404?"记录不存在":error.status===422?"证据完整性异常":"读取失败";return <Alert variant="destructive"><AlertCircle/><AlertTitle>{title}</AlertTitle><AlertDescription className="space-y-3"><p>{error.message}</p><p className="font-mono text-xs">requestId: {error.requestId}</p>{retry?<Button className="min-h-11" variant="outline" onClick={retry}><RefreshCw/>重试 GET</Button>:null}</AlertDescription></Alert>}
