import { NextRequest, NextResponse } from "next/server";
import { requireAdminCapability } from "@/lib/auth/admin-capabilities";
import { getSupabaseClient } from "@/storage/database/supabase-client";
import { normalizeIndicatorWeights } from "@/lib/analysis/strategy";
import { StrategyGovernanceService } from "@/features/management/strategy-service";
import { runRouteCommand } from "@/features/management/route-command";
export async function GET(request: NextRequest) { const auth = await requireAdminCapability(request, "admin:view"); if (!auth.ok) return NextResponse.json({ success:false,error:auth.error }, { status:auth.status }); const { data, error } = await getSupabaseClient().from("strategy_versions").select("version,name,status,weights,model_version,parent_version,effective_from,published_at,retired_at,created_at").order("created_at", { ascending:false }).limit(100); if (error) return NextResponse.json({ success:false,error:"策略暂时不可用" }, { status:503 }); return NextResponse.json({ success:true,items:(data||[]).map(row => ({ ...row, weights:normalizeIndicatorWeights(row.weights) })) }); }
export async function POST(request: NextRequest) { const auth = await requireAdminCapability(request, "admin:configure"); if (!auth.ok) return NextResponse.json({ success:false,error:auth.error }, { status:auth.status }); return runRouteCommand(request, auth.principal, "strategy.create-draft", payload => new StrategyGovernanceService(getSupabaseClient()).createDraft(payload, auth.principal.actorId)); }
export async function PATCH(request: NextRequest) { const auth = await requireAdminCapability(request, "admin:dangerous"); if (!auth.ok) return NextResponse.json({ success:false,error:auth.error }, { status:auth.status }); return runRouteCommand(request, auth.principal, "strategy.lifecycle", async (payload, targetId) => { const service = new StrategyGovernanceService(getSupabaseClient()); const version = typeof payload.version === "string" ? payload.version : ""; if (!version) throw new Error("version required"); return targetId === "strategy.publish" ? service.publish(version, payload) : service.rollback(version, auth.principal.actorId); }); }
