import "server-only";
import { deepFreeze } from "./normalization";
import type { MatrixCell, RunListItem } from "./admin-query-contracts";
import type { AdminQueryCursorPayload } from "./admin-query-cursor";
import type { PageRequest, PagedQueryItem, PredictionFilters, QuerySqlClient, RunFilters, RunScopedFilters, SettlementFilters, StrategyLabAdminQueryRepository } from "./admin-query-repository";

type Row=Record<string,unknown>;
const strategies=["A","B","C","D"] as const;
const checkpoints=["T1215","T30","T03"] as const;
const text=(value:unknown)=>value==null?"":String(value);
const number=(value:unknown)=>Number(value??0);
const iso=(value:unknown)=>new Date(String(value)).toISOString();
const object=(value:unknown):Record<string,unknown>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
const direction=(sort:"created_desc"|"created_asc")=>sort==="created_desc"?"DESC":"ASC";
const tupleWhere=(parameters:unknown[],cursor:AdminQueryCursorPayload|undefined,sort:"created_desc"|"created_asc",alias:string)=>{if(!cursor)return "";parameters.push(cursor.lastCreatedAt,cursor.lastId);const operator=sort==="created_desc"?"<":">";return ` AND (${alias}.created_at,${alias}.id) ${operator} ($${parameters.length-1}::timestamptz,$${parameters.length}::uuid)`;};
const LATEST_SETTLEMENT=`ranked_settlements AS (SELECT s.*,row_number() OVER(PARTITION BY s.prediction_id ORDER BY s.revision DESC,s.created_at DESC,s.id DESC) rn FROM strategy_lab_settlements s),latest_settlements AS (SELECT * FROM ranked_settlements WHERE rn=1)`;
const ELIGIBLE=`run_policy AS (SELECT r.id run_id,r.dataset_cutoff_at,pa.leagues FROM strategy_lab_experiment_runs r JOIN strategy_lab_league_policy_captures pc ON pc.id=(r.configuration->'policy'->>'captureId')::uuid JOIN strategy_lab_league_policy_artifacts pa ON pa.content_hash=pc.artifact_hash WHERE r.id=$1),eligible_predictions AS (SELECT p.* FROM strategy_lab_predictions p JOIN run_policy rp ON rp.run_id=p.run_id JOIN LATERAL (SELECT mf.league_name_normalized FROM strategy_lab_match_facts mf WHERE mf.match_id=p.match_id AND mf.match_date=p.match_date AND mf.dataset_cutoff_at<=rp.dataset_cutoff_at ORDER BY mf.source_observed_at DESC,mf.revision DESC,mf.id DESC LIMIT 1) fact ON TRUE WHERE rp.leagues ? fact.league_name_normalized AND (p.requested_strategy<>'D' OR p.source='d_compat_shadow'))`;

export class PostgresStrategyLabAdminQueryRepository implements StrategyLabAdminQueryRepository{
 constructor(private readonly sql:QuerySqlClient){}

 async listRuns(input:PageRequest<RunFilters>):Promise<readonly RunListItem[]>{const p:unknown[]=[];const where:string[]=[];const add=(v:unknown)=>{p.push(v);return `$${p.length}`};if(input.filters.status)where.push(`r.status=${add(input.filters.status)}`);if(input.filters.runType)where.push(`r.run_type=${add(input.filters.runType)}`);if(input.filters.from)where.push(`r.start_date>=${add(input.filters.from)}`);if(input.filters.to)where.push(`r.end_date<=${add(input.filters.to)}`);if(input.filters.q){const key=add(`%${input.filters.q}%`);where.push(`(r.id::text ILIKE ${key} OR r.code_version ILIKE ${key})`);}const cursor=tupleWhere(p,input.cursor,input.filters.sort,"r");p.push(input.limit);const order=direction(input.filters.sort);const result=await this.sql.query<Row>(`WITH ${LATEST_SETTLEMENT} SELECT r.*,count(DISTINCT pr.id)::int prediction_count,count(DISTINCT (pr.match_id,pr.match_date))::int match_count,count(DISTINCT ls.prediction_id)::int settled_count,CASE WHEN bool_or(cr.status='audit_pending') THEN 'audit_pending' WHEN bool_or(cr.status='audited') THEN 'audited' ELSE 'none' END audit_status FROM strategy_lab_experiment_runs r LEFT JOIN strategy_lab_predictions pr ON pr.run_id=r.id LEFT JOIN latest_settlements ls ON ls.prediction_id=pr.id LEFT JOIN strategy_lab_command_receipts cr ON cr.result_id=r.id WHERE ${where.length?where.join(" AND "):"TRUE"}${cursor} GROUP BY r.id ORDER BY r.created_at ${order},r.id ${order} LIMIT $${p.length}`,p);return deepFreeze(result.rows.map(runDto)) as readonly RunListItem[];}

 async runOverview(runId:string){return this.sql.transaction(async tx=>{const run=(await tx.query<Row>(`SELECT r.*,pc.artifact_hash policy_artifact_hash,pc.id policy_capture_id,pc.captured_at policy_captured_at,pa.mode policy_mode FROM strategy_lab_experiment_runs r LEFT JOIN strategy_lab_league_policy_captures pc ON pc.id=(r.configuration->'policy'->>'captureId')::uuid LEFT JOIN strategy_lab_league_policy_artifacts pa ON pa.content_hash=pc.artifact_hash WHERE r.id=$1`,[runId])).rows[0];if(!run)return null;const summary=(await tx.query<Row>(`WITH ${LATEST_SETTLEMENT},${ELIGIBLE} SELECT count(*)::int predictions,count(DISTINCT (p.match_id,p.match_date))::int matches,count(*) FILTER(WHERE p.decision_status='recommend')::int recommend,count(*) FILTER(WHERE p.decision_status='observe')::int observe,count(*) FILTER(WHERE p.decision_status='reanalyze_required')::int reanalyze,count(*) FILTER(WHERE p.decision_status='insufficient_data')::int insufficient,count(*) FILTER(WHERE p.requested_strategy='C' AND p.executed_strategy='A')::int fallback,count(*) FILTER(WHERE p.requested_strategy='D')::int baseline FROM eligible_predictions p LEFT JOIN latest_settlements ls ON ls.prediction_id=p.id`,[runId])).rows[0]??{};return deepFreeze({run:runDto(run),coverage:{predictions:number(summary.predictions),matches:number(summary.matches),recommend:number(summary.recommend),observe:number(summary.observe),reanalyze:number(summary.reanalyze),insufficient:number(summary.insufficient),cFallback:number(summary.fallback),dBaseline:number(summary.baseline)},policy:{capture:{mode:run.policy_mode??"unknown",artifactHash:run.policy_artifact_hash??null,captureId:run.policy_capture_id??null,capturedAt:run.policy_captured_at?iso(run.policy_captured_at):null},currentChanged:"unknown"},health:{reader:"ready"},metricDefinitions:definitions()});},{readOnly:true,isolationLevel:"repeatable read"});}

 async runMatrix(runId:string):Promise<readonly MatrixCell[]|null>{return this.sql.transaction(async tx=>{if(!(await tx.query<Row>(`SELECT id FROM strategy_lab_experiment_runs WHERE id=$1`,[runId])).rows[0])return null;const result=await tx.query<Row>(`WITH ${LATEST_SETTLEMENT},${ELIGIBLE} SELECT p.requested_strategy,p.checkpoint_type,count(*)::int sample,count(*) FILTER(WHERE p.decision_status='recommend')::int recommend,count(*) FILTER(WHERE p.decision_status='observe')::int observe,count(*) FILTER(WHERE p.decision_status='reanalyze_required')::int reanalyze,count(*) FILTER(WHERE p.decision_status='insufficient_data')::int insufficient,count(*) FILTER(WHERE p.requested_strategy='C' AND p.executed_strategy='A')::int fallback,count(*) FILTER(WHERE ss.status='ready')::int quality_ready,count(*) FILTER(WHERE ss.status='partial')::int quality_partial,count(*) FILTER(WHERE ss.status='insufficient')::int quality_insufficient,count(*) FILTER(WHERE ss.status='invalid')::int quality_invalid,count(*) FILTER(WHERE ss.status='missing')::int quality_missing,${metricSql("actual")},${metricSql("theoretical")} FROM eligible_predictions p JOIN strategy_lab_snapshot_sets ss ON ss.id=p.snapshot_set_id LEFT JOIN latest_settlements ls ON ls.prediction_id=p.id GROUP BY p.requested_strategy,p.checkpoint_type`,[runId]);const rows=new Map(result.rows.map(row=>[`${row.requested_strategy}:${row.checkpoint_type}`,row]));return deepFreeze(strategies.flatMap(strategy=>checkpoints.map(checkpoint=>cell(strategy,checkpoint,rows.get(`${strategy}:${checkpoint}`))))) as readonly MatrixCell[];},{readOnly:true,isolationLevel:"repeatable read"});}

 async runReport(runId:string){return this.sql.transaction(async tx=>{if(!(await tx.query<Row>(`SELECT id FROM strategy_lab_experiment_runs WHERE id=$1`,[runId])).rows[0])return null;const row=(await tx.query<Row>(`WITH ${LATEST_SETTLEMENT},${ELIGIBLE} SELECT count(*)::int valid_sample,count(DISTINCT (p.match_id,p.match_date))::int matches,count(*) FILTER(WHERE p.decision_status='recommend')::int recommend,count(*) FILTER(WHERE p.decision_status='observe')::int observe,count(*) FILTER(WHERE p.decision_status='reanalyze_required')::int reanalyze,count(*) FILTER(WHERE p.decision_status='insufficient_data')::int insufficient,count(*) FILTER(WHERE p.requested_strategy='C' AND p.executed_strategy='A')::int fallback,count(*) FILTER(WHERE p.requested_strategy='D')::int baseline,${metricSql("actual")},${metricSql("theoretical")} FROM eligible_predictions p LEFT JOIN latest_settlements ls ON ls.prediction_id=p.id`,[runId])).rows[0]??{};return deepFreeze({validSample:number(row.valid_sample),coverage:{matches:number(row.matches),recommend:number(row.recommend),observe:number(row.observe),reanalyze:number(row.reanalyze),insufficient:number(row.insufficient)},cFallback:number(row.fallback),dBaseline:number(row.baseline),actual:metric(row,"actual"),theoretical:metric(row,"theoretical"),metricDefinitions:definitions(),timeSeries:null});},{readOnly:true,isolationLevel:"repeatable read"});}

 async listSnapshots(input:PageRequest<RunScopedFilters>):Promise<readonly PagedQueryItem[]>{const p:unknown[]=[input.filters.runId];const cursor=tupleWhere(p,input.cursor,input.filters.sort,"s");p.push(input.limit);const order=direction(input.filters.sort);const result=await this.sql.query<Row>(`SELECT s.*,CASE WHEN s.dataset_mode='strict_asof' AND s.source_cutoff_at<=s.checkpoint_at THEN 'verified' WHEN s.dataset_mode='strict_asof' THEN 'failed' ELSE 'unknown' END asof_status,CASE WHEN (s.checkpoint_type='T1215' AND s.previous_snapshot_set_id IS NULL) OR (s.checkpoint_type<>'T1215' AND s.previous_snapshot_set_id IS NOT NULL) THEN 'verified' ELSE 'failed' END predecessor_status FROM strategy_lab_snapshot_sets s WHERE s.run_id=$1${cursor} ORDER BY s.created_at ${order},s.id ${order} LIMIT $${p.length}`,p);return deepFreeze(result.rows.map(snapshotDto)) as readonly PagedQueryItem[];}

 async listPredictions(input:PageRequest<PredictionFilters>):Promise<readonly PagedQueryItem[]>{const p:unknown[]=[input.filters.runId];const where:string[]=["p.run_id=$1"];const add=(v:unknown)=>{p.push(v);return `$${p.length}`};if(input.filters.q){const key=add(`%${input.filters.q}%`);where.push(`(p.id::text ILIKE ${key} OR p.match_id ILIKE ${key})`);}if(input.filters.strategy)where.push(`p.requested_strategy=${add(input.filters.strategy)}`);if(input.filters.checkpoint)where.push(`p.checkpoint_type=${add(input.filters.checkpoint)}`);if(input.filters.status)where.push(`p.decision_status=${add(input.filters.status)}`);const cursor=tupleWhere(p,input.cursor,input.filters.sort,"p");p.push(input.limit);const order=direction(input.filters.sort);const result=await this.sql.query<Row>(`SELECT p.*,s.status snapshot_status,s.content_hash snapshot_hash FROM strategy_lab_predictions p JOIN strategy_lab_snapshot_sets s ON s.id=p.snapshot_set_id WHERE ${where.join(" AND ")}${cursor} ORDER BY p.created_at ${order},p.id ${order} LIMIT $${p.length}`,p);return deepFreeze(result.rows.map(predictionDto)) as readonly PagedQueryItem[];}

 async listSettlements(input:PageRequest<SettlementFilters>):Promise<readonly PagedQueryItem[]>{const p:unknown[]=[input.filters.runId];let basis="";if(input.filters.quoteBasis){p.push(input.filters.quoteBasis);basis=` AND x.quote_basis=$${p.length}`;}const cursor=tupleWhere(p,input.cursor,input.filters.sort,"x");p.push(input.limit);const latest=input.filters.history?"":" AND x.rn=1";const order=direction(input.filters.sort);const result=await this.sql.query<Row>(`SELECT x.*,round(x.profit_units*1000000)::text profit_micros_exact FROM (SELECT s.*,pr.run_id,pr.match_id,pr.match_date,pr.requested_strategy,row_number() OVER(PARTITION BY s.prediction_id ORDER BY s.revision DESC,s.created_at DESC,s.id DESC) rn FROM strategy_lab_settlements s JOIN strategy_lab_predictions pr ON pr.id=s.prediction_id WHERE pr.run_id=$1) x WHERE TRUE${latest}${basis}${cursor} ORDER BY x.created_at ${order},x.id ${order} LIMIT $${p.length}`,p);return deepFreeze(result.rows.map(settlementDto)) as readonly PagedQueryItem[];}

 async settlementChain(predictionId:string){const prediction=(await this.sql.query<Row>(`SELECT p.*,s.status snapshot_status,s.content_hash snapshot_hash FROM strategy_lab_predictions p JOIN strategy_lab_snapshot_sets s ON s.id=p.snapshot_set_id WHERE p.id=$1`,[predictionId])).rows[0];if(!prediction)return null;const rows=(await this.sql.query<Row>(`SELECT s.*,round(s.profit_units*1000000)::text profit_micros_exact,mr.content_hash score_revision_hash,mr.revision score_revision FROM strategy_lab_settlements s LEFT JOIN strategy_lab_match_result_revisions mr ON mr.id=s.match_result_revision_id WHERE s.prediction_id=$1 ORDER BY s.revision,s.id`,[predictionId])).rows;let valid=true;for(let index=0;index<rows.length;index++){const current=rows[index],previous=rows[index-1];if(number(current.revision)!==index+1||(index===0?current.supersedes!=null:text(current.supersedes)!==text(previous.id)))valid=false;if(previous&&["quote_basis","actual_quote_snapshot_id","quote_handicap_raw","quote_handicap_quarter_units","quote_selected_water_millionths"].some(key=>text(current[key])!==text(previous[key])))valid=false;}if(!valid)throw Object.assign(new Error("settlement chain integrity"),{code:"integrity_error"});return deepFreeze({prediction:predictionDto(prediction),integrity:{revision:"verified",quoteDrift:"verified"},revisions:rows.map((row,index)=>({...settlementDto(row),scoreRevision:row.score_revision==null?null:number(row.score_revision),scoreRevisionHash:row.score_revision_hash?text(row.score_revision_hash):null,current:index===rows.length-1,superseded:index<rows.length-1,excludedFromStatistics:index<rows.length-1||!Boolean(row.is_counted)}))});}

 async runAudit(input:PageRequest<RunScopedFilters>):Promise<readonly PagedQueryItem[]|null>{if(!(await this.sql.query<Row>(`SELECT id FROM strategy_lab_experiment_runs WHERE id=$1`,[input.filters.runId])).rows[0])return null;const p:unknown[]=[input.filters.runId];const cursor=tupleWhere(p,input.cursor,input.filters.sort,"cr");p.push(input.limit);const order=direction(input.filters.sort);const result=await this.sql.query<Row>(`SELECT cr.id,cr.action,cr.status,cr.result_type,cr.result_id,cr.actor_id,cr.request_id,cr.audit_attempts,cr.last_audit_error_code,cr.created_at,cr.updated_at,cr.audited_at,left(cr.payload_hash,12) payload_hash_short,left(cr.operation_key,8)||'…'||right(cr.operation_key,4) operation_key_masked FROM strategy_lab_command_receipts cr WHERE (cr.result_id=$1 OR cr.result_id IN(SELECT id FROM strategy_lab_predictions WHERE run_id=$1 UNION SELECT id FROM strategy_lab_snapshot_sets WHERE run_id=$1 UNION SELECT st.id FROM strategy_lab_settlements st JOIN strategy_lab_predictions pr ON pr.id=st.prediction_id WHERE pr.run_id=$1))${cursor} ORDER BY cr.created_at ${order},cr.id ${order} LIMIT $${p.length}`,p);return deepFreeze(result.rows.map(auditDto)) as readonly PagedQueryItem[];}
}

function runDto(row:Row):RunListItem{return {id:text(row.id),runType:text(row.run_type),status:text(row.status) as RunListItem["status"],datasetMode:text(row.dataset_mode),startDate:text(row.start_date),endDate:text(row.end_date),datasetCutoffAt:iso(row.dataset_cutoff_at),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at),coverage:{predictions:number(row.prediction_count),matches:number(row.match_count),settled:number(row.settled_count)},auditStatus:text(row.audit_status||"none") as RunListItem["auditStatus"]};}
function metricSql(basis:"actual"|"theoretical"){const condition=`ls.quote_basis='${basis}'`;return `count(*) FILTER(WHERE ${condition} AND ls.is_counted)::int ${basis}_counted,count(*) FILTER(WHERE ${condition} AND ls.outcome='unavailable')::int ${basis}_unavailable,count(*) FILTER(WHERE ${condition} AND ls.outcome='win')::int ${basis}_win,count(*) FILTER(WHERE ${condition} AND ls.outcome='half_win')::int ${basis}_half_win,count(*) FILTER(WHERE ${condition} AND ls.outcome='push')::int ${basis}_push,count(*) FILTER(WHERE ${condition} AND ls.outcome='half_loss')::int ${basis}_half_loss,count(*) FILTER(WHERE ${condition} AND ls.outcome='loss')::int ${basis}_loss,COALESCE(round(sum(ls.profit_units) FILTER(WHERE ${condition} AND ls.is_counted)*1000000),0)::text ${basis}_profit_micros,(count(*) FILTER(WHERE ${condition} AND ls.is_counted)*1000000)::text ${basis}_stake_micros,CASE WHEN count(*) FILTER(WHERE ${condition} AND ls.is_counted)>0 THEN (sum(ls.profit_units) FILTER(WHERE ${condition} AND ls.is_counted)/count(*) FILTER(WHERE ${condition} AND ls.is_counted))::text ELSE NULL END ${basis}_roi`;}
function metric(row:Row|undefined,prefix:"actual"|"theoretical"){return {counted:number(row?.[`${prefix}_counted`]),unavailable:number(row?.[`${prefix}_unavailable`]),outcomes:{win:number(row?.[`${prefix}_win`]),halfWin:number(row?.[`${prefix}_half_win`]),push:number(row?.[`${prefix}_push`]),halfLoss:number(row?.[`${prefix}_half_loss`]),loss:number(row?.[`${prefix}_loss`])},profitMicros:text(row?.[`${prefix}_profit_micros`]??"0"),stakeMicros:text(row?.[`${prefix}_stake_micros`]??"0"),roi:row?.[`${prefix}_roi`]==null?null:text(row[`${prefix}_roi`])};}
function cell(strategy:"A"|"B"|"C"|"D",checkpoint:"T1215"|"T30"|"T03",row:Row|undefined):MatrixCell{return {strategy,checkpoint,executable:strategy!=="D",compatibilityOnly:strategy==="D",sample:number(row?.sample),decisions:{recommend:number(row?.recommend),observe:number(row?.observe),reanalyze:number(row?.reanalyze),insufficient:number(row?.insufficient)},fallback:number(row?.fallback),snapshotQuality:{ready:number(row?.quality_ready),partial:number(row?.quality_partial),insufficient:number(row?.quality_insufficient),invalid:number(row?.quality_invalid),missing:number(row?.quality_missing)},actual:metric(row,"actual"),theoretical:metric(row,"theoretical")};}
function snapshotDto(row:Row):PagedQueryItem{return {id:text(row.id),matchId:text(row.match_id),matchDate:text(row.match_date),checkpoint:text(row.checkpoint_type),checkpointAt:iso(row.checkpoint_at),datasetMode:text(row.dataset_mode),status:text(row.status),previousSnapshotSetId:row.previous_snapshot_set_id?text(row.previous_snapshot_set_id):null,revision:number(row.revision),supersedesSnapshotSetId:row.supersedes_snapshot_set_id?text(row.supersedes_snapshot_set_id):null,sourceCutoffAt:iso(row.source_cutoff_at),contentHash:text(row.content_hash),schemaVersion:number(row.schema_version),completeness:object(row.completeness),createdAt:iso(row.created_at),integrity:{hashVerification:"constraint_verified",asof:text(row.asof_status),predecessor:text(row.predecessor_status),revision:number(row.revision)>0?"verified":"failed"}};}
function predictionDto(row:Row):PagedQueryItem{return {id:text(row.id),runId:text(row.run_id),matchId:text(row.match_id),matchDate:text(row.match_date),checkpoint:text(row.checkpoint_type),snapshotSetId:text(row.snapshot_set_id),requestedStrategy:text(row.requested_strategy),executedStrategy:text(row.executed_strategy),fallback:row.requested_strategy==="C"&&row.executed_strategy==="A",fallbackReason:row.fallback_reason?text(row.fallback_reason):null,compatibilityOnly:row.requested_strategy==="D",executable:row.requested_strategy!=="D",decisionStatus:text(row.decision_status),selection:row.selection?text(row.selection):null,reasonCode:text(row.reason_code),branchId:text(row.branch_id),inputHash:text(row.input_hash),outputHash:text(row.output_hash),snapshotStatus:text(row.snapshot_status),snapshotHash:text(row.snapshot_hash),evidenceContractVersion:number(row.evidence_contract_version),createdAt:iso(row.created_at)};}
function settlementDto(row:Row):PagedQueryItem{return {id:text(row.id),predictionId:text(row.prediction_id),revision:number(row.revision),quoteBasis:text(row.quote_basis),outcome:text(row.outcome),profitMicros:row.profit_micros_exact==null?null:text(row.profit_micros_exact),isCounted:Boolean(row.is_counted),settlementBasis:text(row.settlement_basis),actualQuoteSnapshotId:row.actual_quote_snapshot_id==null?null:number(row.actual_quote_snapshot_id),evidenceHash:row.evidence_hash?text(row.evidence_hash):null,calculatorVersion:row.calculator_version?text(row.calculator_version):null,quoteHandicapRaw:row.quote_handicap_raw?text(row.quote_handicap_raw):null,quoteSelectedWaterMillionths:row.quote_selected_water_millionths==null?null:number(row.quote_selected_water_millionths),supersedes:row.supersedes?text(row.supersedes):null,settledAt:iso(row.settled_at),createdAt:iso(row.created_at)};}
function auditDto(row:Row):PagedQueryItem{return {id:text(row.id),action:text(row.action),status:text(row.status),resultType:text(row.result_type),resultId:text(row.result_id),actorId:mask(text(row.actor_id)),requestId:text(row.request_id),auditAttempts:number(row.audit_attempts),lastAuditErrorCode:row.last_audit_error_code?text(row.last_audit_error_code):null,payloadHashShort:text(row.payload_hash_short),operationKeyMasked:text(row.operation_key_masked),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at),auditedAt:row.audited_at?iso(row.audited_at):null};}
function definitions(){return {sample:"requested strategy decisions within frozen policy membership",counted:"latest settlement revisions with is_counted=true",unavailable:"latest unavailable settlements excluded from denominator",profitMicros:"profit units multiplied by 1,000,000",stakeMicros:"counted predictions multiplied by 1,000,000",roi:"profitMicros / stakeMicros",actual:"authoritative executable quote",theoretical:"model quote; not an actually tradable quote"};}
function mask(value:string){return value.length<=4?"***":`${value.slice(0,2)}***${value.slice(-2)}`;}
